### PR TITLE
Transform the Quick fixes related to ModifyModifiersProposal to implement the code action

### LINKED ISSUE #543: Transform the Quick fixes related to ModifyModifiersProposal to implement the code action participant extension point.
See the initial work completed here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/312.

In addition to refactoring the code, the code action participants will need to be added to the plugin.xml and the relevant Jakarta EE code action tests should be enabled.

### PR DESCRIPTION
**Pull request by vaisakhkannan**
Fixes #543  --> Transform the Quick fixes related to ModifyModifiersProposal to implement the code action

### CODE REVIEW

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java [hunk 1]
```diff
@@ -1,82 +1,138 @@
...
+    @Override
+    public CodeAction resolveCodeAction(JavaCodeActionResolveContext context) {
+
+        final CodeAction toResolve = context.getUnresolved();
+        List<Diagnostic> diagnostics = toResolve.getDiagnostics();
+
+
+        String message = toResolve.getTitle();
+
+        if (message == Messages.getMessage("RemoveStaticModifier")) {
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java:67]: Should use equals() when comparing Strings unless you're absolutely sure that you require a reference to the same String object.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NoResourcePublicConstructorQuickFix.java [hunk 2]
```diff
@@ -18,64 +18,98 @@
...
             JavaCodeActionContext targetContext = context.copy();
             node = targetContext.getCoveredNode();
             PsiClass parentType = PsiTreeUtil.getParentOfType(node, PsiClass.class);
             parentMethod = PsiTreeUtil.getParentOfType(node, PsiMethod.class);
 
-            ChangeCorrectionProposal proposal = new ModifyModifiersProposal(TITLE_MESSAGE, targetContext.getSource().getCompilationUnit(),
-                    targetContext.getASTRoot(), parentType, 0, parentMethod.getModifierList(), Collections.singletonList("public"));
+            String message = toResolve.getTitle();
+
+            if (message == Messages.getMessage("MakeConstructorPublic")) {
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NoResourcePublicConstructorQuickFix.java:87]: Should use equals() when comparing Strings unless you're absolutely sure that you require a reference to the same String object.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NoResourcePublicConstructorQuickFix.java [hunk 3]
```diff
@@ -18,64 +18,98 @@
...
+                } catch (Exception e) {
+                    LOGGER.log(Level.WARNING, "Unable to create workspace edit for code action to make constructor public", e);
+                }
 
-            final PsiParameterList list = parentMethod.getParameterList();
-            if (list != null && list.getParametersCount() > 0) {
-                targetContext = context.copy();
-                node = targetContext.getCoveredNode();
-                parentType = PsiTreeUtil.getParentOfType(node, PsiClass.class);
+            } else if (message == Messages.getMessage("NoargPublicConstructor")) {
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NoResourcePublicConstructorQuickFix.java:99]: Should use equals() when comparing Strings unless you're absolutely sure that you require a reference to the same String object.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java [hunk 4]
```diff
@@ -1,82 +1,138 @@
...
+
+    private void resolveRemoveConstraintAnnotationsCodeAction(JavaCodeActionResolveContext context, Diagnostic diagnostic) {
+
+        final CodeAction toResolve = context.getUnresolved();
         final PsiElement node = context.getCoveredNode();
         final PsiClass parentType = PsiTreeUtil.getParentOfType(node, PsiClass.class);
-        final PsiModifierListOwner modifierListOwner = PsiTreeUtil.getParentOfType(node, PsiModifierListOwner.class);
-
         final String annotationName = diagnostic.getData().toString().replace("\"", "");
+        final String name = Messages.getMessage("RemoveConstraintAnnotation", annotationName);
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java:90]: I noticed the same messages are being retrieved/computed multiple times. Isn't this already available from the `CodeAction` object that you created?

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NoResourcePublicConstructorQuickFix.java [hunk 5]
```diff
@@ -18,64 +18,98 @@
...
             PsiClass parentType = PsiTreeUtil.getParentOfType(node, PsiClass.class);
             parentMethod = PsiTreeUtil.getParentOfType(node, PsiMethod.class);
 
-            ChangeCorrectionProposal proposal = new ModifyModifiersProposal(TITLE_MESSAGE, targetContext.getSource().getCompilationUnit(),
-                    targetContext.getASTRoot(), parentType, 0, parentMethod.getModifierList(), Collections.singletonList("public"));
+            String message = toResolve.getTitle();
+
+            if (message.equals(Messages.getMessage("MakeConstructorPublic"))) {
+
+                ChangeCorrectionProposal proposal = new ModifyModifiersProposal(Messages.getMessage("MakeConstructorPublic"), targetContext.getSource().getCompilationUnit(),
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NoResourcePublicConstructorQuickFix.java:89]: I noticed the same messages are being retrieved/computed multiple times. The value of the message was just checked above. You can pass that string directly to the constructor.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NoResourcePublicConstructorQuickFix.java [hunk 6]
```diff
@@ -18,64 +18,98 @@
...
-            final PsiParameterList list = parentMethod.getParameterList();
-            if (list != null && list.getParametersCount() > 0) {
-                targetContext = context.copy();
-                node = targetContext.getCoveredNode();
-                parentType = PsiTreeUtil.getParentOfType(node, PsiClass.class);
+            } else if (message.equals(Messages.getMessage("NoargPublicConstructor"))) {
 
-                final String name = Messages.getMessage("NoargPublicConstructor");
-                proposal = new AddConstructorProposal(name,
+                ChangeCorrectionProposal proposal = new AddConstructorProposal(Messages.getMessage("NoargPublicConstructor"),
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/NoResourcePublicConstructorQuickFix.java:101]: I noticed the same messages are being retrieved/computed multiple times. The value of the message was just checked above. You can pass that string directly to the constructor.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java [hunk 7]
```diff
@@ -1,82 +1,138 @@
...
+    }
+
+    private void resolveRemoveConstraintAnnotationsCodeAction(JavaCodeActionResolveContext context, Diagnostic diagnostic) {
+
+        final CodeAction toResolve = context.getUnresolved();
         final PsiElement node = context.getCoveredNode();
         final PsiClass parentType = PsiTreeUtil.getParentOfType(node, PsiClass.class);
-        final PsiModifierListOwner modifierListOwner = PsiTreeUtil.getParentOfType(node, PsiModifierListOwner.class);
-
         final String annotationName = diagnostic.getData().toString().replace("\"", "");
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java:89]: You already computed the annotation name when you created the code action. It would be better to store that value in the code action and then retrieve it in the resolve method. See discussion here: https://github.com/OpenLiberty/liberty-tools-intellij/pull/575 about storing custom data in the `CodeActionResolveData` using the extendedData HashMap. Aparna has added a utility method that you can use in this PR: https://github.com/OpenLiberty/liberty-tools-intellij/pull/594.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java [hunk 8]
```diff
@@ -1,82 +1,138 @@
...
+
+
+        String message = toResolve.getTitle();
+
+        if (message.equals(Messages.getMessage("RemoveStaticModifier"))) {
+            resolveStaticModifierCodeAction(context);
+            return toResolve;
+        }
+
+        resolveRemoveConstraintAnnotationsCodeAction(context, diagnostics.size() > 0 ? diagnostics.get(0) : null);
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java:72]: Related to my comment about retrieving the annotation name from `CodeActionResolveData`, I think you're only searching for the diagnostic here so you can compute the annotation name again. Looks like you could remove that parameter. This would also eliminate any risk of getting a `NullPointerException` since the reference is being used without checking whether it's `null` in the method.

**Review by mrglavas — CHANGES_REQUESTED** [review]
See comments for requested changes.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java [hunk 9]
```diff
@@ -1,82 +1,148 @@
...
+
+    @Override
+    public String getParticipantId() {
+        return BeanValidationQuickFix.class.getName();
+    }
 
     public List<? extends CodeAction> getCodeActions(JavaCodeActionContext context, Diagnostic diagnostic) {
         List<CodeAction> codeActions = new ArrayList<>();
-        removeConstraintAnnotations(diagnostic, context.copy(), codeActions);
+        getRemoveConstraintAnnotationsCodeActions(diagnostic, context, codeActions);
```
Comment (aparnamichael) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java:53]: can we update the method name as removeConstraintAnnotationsCodeActions ? This method is not a getter method, so I think it is better to remove 'get' from the method name.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java [hunk 10]
```diff
@@ -1,82 +1,148 @@
...
 
         if (diagnostic.getCode().getLeft().equals(BeanValidationConstants.DIAGNOSTIC_CODE_STATIC)) {
-            removeStaticModifier(diagnostic, context.copy(), codeActions);
+            getRemoveStaticModifierCodeActions(diagnostic, context, codeActions);
```
Comment (aparnamichael) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationQuickFix.java:56]: same as my above comment

**Comment by mezarin** [comment]
@vaisakhkannan, just wanted to mention that, for completeness, the PR solving https://github.com/eclipse/lsp4jakarta/issues/505, addresses a bit more than what you have in your PR. Please see the PR associated with the mentioned issue.

**Comment by vaisakhkannan** [comment]
I just want to mention that I modified the **_messages.properties_** file, changing the value as shown below for **_#NoResourcePublicConstructorQuickFix._**
`NoargPublicConstructor = Add a default 'public' constructor to this class`

Before changing the line,
 https://github.com/OpenLiberty/liberty-tools-intellij/blob/7b6689af4c8f9afd2e36ca3c05798c0362e702c7/src/main/resources/org/eclipse/lsp4jakarta/jdt/core/messages/messages.properties#L114

**Review by anusreelakshmi934 — APPROVED** [review]

**Review by mrglavas — APPROVED** [review]
Verified that my previous comments were addressed. Looks good. Thanks.
