### PR TITLE
Fixes #512 - Transform the Quick Fixes which extends InsertAnnotationQuickFix to implement the code action participant extension point

### LINKED ISSUE #512: Transform the Quick Fixes which extends InsertAnnotationQuickFix to implement the code action participant extension point.
See the initial work completed here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/305.

In addition to refactoring the code, the code action participants will need to be added to the plugin.xml and the relevant Jakarta EE code action tests should be enabled.

### PR DESCRIPTION
**Pull request by aparnamichael**
Fixes #512  - Transform the Quick Fixes which extends InsertAnnotationQuickFix to implement the code action participant extension point

Enabled code actions test as well

### CODE REVIEW

**Review by dessina-devasia — APPROVED** [review]

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationQuickFix.java [hunk 1]
```diff
@@ -112,4 +131,16 @@ protected PsiModifierListOwner getBinding(PsiElement node) {
     protected String getLabel(String annotationName, String... attributes) {
         return Messages.getMessage("InsertItem", "@" + annotation); // uses Java syntax
     }
+
+    private CodeAction createCodeAction(JavaCodeActionContext context, Diagnostic diagnostic, String label) {
```
Comment (aparnamichael) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationQuickFix.java:135]: @mrglavas - can we raise a separate PR for moving this method to a common file?

Comment (mrglavas) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationQuickFix.java:135]: @aparnamichael Yes. Feel free to open a separate issue and PR for this. Thanks.

Comment (aparnamichael) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationQuickFix.java:135]: Created PR for the same - https://github.com/OpenLiberty/liberty-tools-intellij/pull/531

**Review by mrglavas — APPROVED** [review]
