### PR TITLE
Fixes #589 - Refactoring of Quick Fix class RemoveInvalidInjectParamAnnotationQuickFix

### LINKED ISSUE #589: Transform the Quick Fix class RemoveInvalidInjectParamAnnotationQuickFix to implement the code action participant extension point.
See the initial work completed here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/314.

In addition to refactoring the code, the code action participants will need to be added to the plugin.xml and the relevant Jakarta EE code action tests should be enabled.

### PR DESCRIPTION
**Pull request by anusreelakshmi934**
Fixes #589 
Refactored and modified the test cases

### CODE REVIEW

File: src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java [hunk 1]
```diff
@@ -217,96 +217,99 @@ public void injectAndDisposesObservesObservesAsync() throws Exception {
...
...nject\n    public String greetObserves(@Observes String name) {\n        return \"Hi \" + name + \"!\";\n    }\n\n\n    @Inject\n    public String greetObservesAsync(@ObservesAsync String name) {\n        return \"Hi \" + name + \"!\";\n    }\n\n\n    @Inject\n    public String greetDisposesObserves(@Disposes String name1, @Observes String name2) {\n        return \"Hi \" + name1 + \" and \" + name2 + \"!\";\n    }\n\n\n    @Inject\n    public String greetObservesObservesAsync(@Observes String name1, @ObservesAsync String name2) {\n        return \"Hi \" + name1 + \" and \" + name2 + \"!\";\n    }\n\n\n    @Inject\n    public String greetDisposesObservesAsync(@Disposes String name1, @ObservesAsync String name2) {\n        return \"Hi \" + name1 + \" and \" + name2 + \"!\";\n    }\n\n\n    @Inject\n    public String greetDisposesObservesObservesAsync(@Disposes String name1, @Observes String name2, @ObservesAsync String name3) {\n        return \"Hi \" + name1 + \", \" + name2 + \" and \" + name3 + \"!\";\n    }\n\n    @Inject\n    public String greetDisposesObservesObservesAsync2(@Disposes @Observes @ObservesAsync String name) {\n        return \"Hi \" + name + \"!\";\n    }\n}\n");
```
Comment (dessina-devasia) [inline src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java:248]: It will be better to format all TextEdit code snippets

File: src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java [hunk 2]
```diff
@@ -217,96 +217,99 @@ public void injectAndDisposesObservesObservesAsync() throws Exception {
...
...\n\n    @Inject\n    public String greetObserves(String name) {\n        return \"Hi \" + name + \"!\";\n    }\n\n\n    @Inject\n    public String greetObservesAsync(@ObservesAsync String name) {\n        return \"Hi \" + name + \"!\";\n    }\n\n\n    @Inject\n    public String greetDisposesObserves(@Disposes String name1, @Observes String name2) {\n        return \"Hi \" + name1 + \" and \" + name2 + \"!\";\n    }\n\n\n    @Inject\n    public String greetObservesObservesAsync(@Observes String name1, @ObservesAsync String name2) {\n        return \"Hi \" + name1 + \" and \" + name2 + \"!\";\n    }\n\n\n    @Inject\n    public String greetDisposesObservesAsync(@Disposes String name1, @ObservesAsync String name2) {\n        return \"Hi \" + name1 + \" and \" + name2 + \"!\";\n    }\n\n\n    @Inject\n    public String greetDisposesObservesObservesAsync(@Disposes String name1, @Observes String name2, @ObservesAsync String name3) {\n        return \"Hi \" + name1 + \", \" + name2 + \" and \" + name3 + \"!\";\n    }\n\n    @Inject\n    public String greetDisposesObservesObservesAsync2(@Disposes @Observes @ObservesAsync String name) {\n        return \"Hi \" + name + \"!\";\n    }\n}\n");
```
Comment (dessina-devasia) [inline src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java:255]: Consider formatting of code snippet mentioned in TextEdit

**Review by dessina-devasia — DISMISSED** [review]

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java [hunk 3]
```diff
@@ -57,44 +65,66 @@ public List<? extends CodeAction> getCodeActions(JavaCodeActionContext context,
...
+         final PsiClass parentType = getBinding(node);
+         final PsiMethod method = PsiTreeUtil.getParentOfType(node, PsiMethod.class);
+         CodeActionResolveData data = (CodeActionResolveData) toResolve.getData();
+         List<String> annotationsToRemove = new ArrayList<>();
+         int paramIndex = 0;
 
-        final PsiElement node = context.getCoveredNode();
-        final PsiClass parentType = getBinding(node);
-        final PsiMethod method = PsiTreeUtil.getParentOfType(node, PsiMethod.class);
+         if (data.getExtendedDataEntry(ANNOTATION_TO_REMOVE) instanceof List) {
```
Comment (turkeylurkey) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java:97]: If this check fails then we have a serious error. Please add an else statement that logs a message like "The CodeActionResolveData was corrupted somewhere in the LSP layer. Unable to resolve code action." and then return null from resolveCodeAction(). I think null will be passed back to the language server and be ignored but need to test. 

This also applies to the INDEX_KEY case. Log the same message and return null. It may be possible to combine these two checks. 

Now you can remove the default values for annotationsToRemove and paramIndex because they will not be used.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java [hunk 4]
```diff
@@ -57,44 +65,66 @@ public List<? extends CodeAction> getCodeActions(JavaCodeActionContext context,
...
+         final List<PsiAnnotation> psiAnnotationsToRemove = new ArrayList<>();
 
-        RemoveAnnotationsProposal proposal = new RemoveAnnotationsProposal(label, context.getSource().getCompilationUnit(),
-                context.getASTRoot(), parentType, 0, psiAnnotationsToRemove);
-        CodeAction codeAction = context.convertToCodeAction(proposal, diagnostic);
-        if (codeAction != null) {
-            codeActions.add(codeAction);
-        }
-    }
+         List<String> finalAnnotationsToRemove = annotationsToRemove;
```
Comment (turkeylurkey) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/RemoveParamAnnotationQuickFix.java:108]: I don't think you need to create a new variable here, it makes the code harder to understand.

**Review by turkeylurkey — CHANGES_REQUESTED** [review]

**Review by turkeylurkey — APPROVED** [review]
Thank you!

**Review by dessina-devasia — APPROVED** [review]
