### PR TITLE
Fix proj disposed issues

### LINKED ISSUE #272: AlreadyDisposedException using "Liberty: Start" from the "shift shift" menu after opening new project in "This Window"
Using [getting started guide](https://github.com/openliberty/guide-getting-started) and [mp-health guide](https://github.com/openliberty/guide-microprofile-health) (with the `start` directory removed, so there is only one Liberty project)

1. Open the mp-health guide
2. Run `Liberty: Start` from the "shift shift" menu or run "Start" from the Liberty Tool Window - this should run as expected
3. Open (File->Open) the getting started guide project and select "This Window" - the getting started guide should now be open in IntelliJ and the mp-health guide no longer there.
4. Run `Liberty: Start` from the "shift shift" menu - this is when the `AlreadyDisposedException` occurs and the app does not run
5. Subsequent attempts to run `Liberty: Start` from the "shift shift" menu do not result in an exception, but the app still does not run
6. Running "Start" from Liberty Tool Window is successful and resolves this issue - you can now run the project from the "shift shift" menu

If two projects were loaded initially (ie. "start" and "finish"), then the selection dialog in the "shift shift" menu will be populated with the previous open projects. Selecting a project to run results in an `AlreadyDisposedException`. This can be reproduced by opening the getting started guide first and then the mp-health guide.

### PR DESCRIPTION
**Pull request by mezarin**
Fixes #272 

Summarizing the issue:
When a Liberty action is driven on project A, the same action will no longer run on a new project B (open project A-> run action x -> open project B -> run action x)  or the same project if project A is closed and re-opened (open project A -> run action x -> close project A -> re-open project A, run action x) 

Relevant doc: 
https://plugins.jetbrains.com/docs/intellij/basic-action-system.html#action-implementation

The error looks something like this:

```
2023-03-11 14:33:57,080 [11784807] SEVERE - #c.i.i.p.PluginManager - Cannot create org.jetbrains.plugins.terminal.TerminalView because container is already disposed (container=Project(name=single-mod-maven-app, containerState=DISPOSE_COMPLETED, componentStore=/.../github.com/OpenLiberty/liberty-tools-intellij/src/test/resources/apps/maven/single-mod-maven-app) (disposed))
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create org.jetbrains.plugins.terminal.TerminalView because container is already disposed (container=Project(name=single-mod-maven-app, containerState=DISPOSE_COMPLETED, componentStore=/.../github.com/OpenLiberty/liberty-tools-intellij/src/test/resources/apps/maven/single-mod-maven-app) (disposed))
        at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
        at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:701)
        at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:635)
        at org.jetbrains.plugins.terminal.TerminalView.getInstance(TerminalView.java:119)
        at io.openliberty.tools.intellij.util.LibertyProjectUtil.getTerminalWidget(LibertyProjectUtil.java:149)
        at io.openliberty.tools.intellij.actions.LibertyGeneralAction.getTerminalWidget(LibertyGeneralAction.java:201)
        at io.openliberty.tools.intellij.actions.LibertyDevStartContainerAction.executeLibertyAction(LibertyDevStartContainerAction.java:24)
        at io.openliberty.tools.intellij.actions.LibertyGeneralAction.actionPerformed(LibertyGeneralAction.java:137)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:
```

### CODE REVIEW

File: src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStopAction.java [hunk 1]
```diff
@@ -9,19 +9,29 @@
...
 public class LibertyDevStopAction extends LibertyGeneralAction {
 
-    public LibertyDevStopAction() {
-        setActionCmd(LocalizedResourceUtil.getMessage("stop.liberty.dev"));
+    /**
+     * Returns the name of the action command being processed.
+     *
+     * @return The name of the action command being processed.
+     */
+    protected String getActionCommandName() {
```
Comment (evie-lau) [inline src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStopAction.java:26]: Seeing this method in a lot of Actions. Would it be good to refactor this method into the abstract class along with setting a String to store the message key?

Comment (mezarin) [reply src/main/java/io/openliberty/tools/intellij/actions/LibertyDevStopAction.java:26]: Hi Evie, the getActionCommandName() is an abstract method that is already in the abstract class LibertyGeneralAction. It is just that there are 12 different different commands/actions that implement it. Note that we cannot store data inside the abstract class. Data caching is what led to the issue this PR is attempting to fix, and it goes against documented restrictions (see doc link above).

**Comment by TrevCraw** [comment]
After testing, looks like this PR will also fix https://github.com/OpenLiberty/liberty-tools-intellij/issues/271

**Review by TrevCraw — APPROVED** [review]
