### PR TITLE
Add a collection of 5 quick fixes which extend InsertAnnotationMissingQuickFix

### LINKED ISSUE #304: Enable Quick Fixes which extend InsertAnnotationMissingQuickFix
Part of #103 

The following quick fixes extend the base class:

- [x] ManagedBeanConstructorQuickFix
- [x] CompleteFilterAnnotationQuickFix
- [x] CompleteServletAnnotationQuickFix
- [x] ManagedBeanQuickFix
- [x] PersistenceAnnotationQuickFix

### PR DESCRIPTION
**Pull request by turkeylurkey**
All these quick fixes modify annotations. 

Fixes #304

### CODE REVIEW

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+    }
+
+    private static final String[] REMOVE_ANNOTATION_NAMES = new ArrayList<>(SCOPE_FQ_NAMES).toArray(new String[SCOPE_FQ_NAMES.size()]);
+
+    @Override
+    protected void insertAnnotations(Diagnostic diagnostic, JavaCodeActionContext context,
+                                     List<CodeAction> codeActions) {
+        String[] annotations = getAnnotations();
+        for (String annotation : annotations) {
+            insertAndReplaceAnnotation(diagnostic, context, codeActions, annotation);
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java:45]: Seeing this loop here is misleading as it looks like annotations.length == 1 all the time, but if it ever becomes possible that this generates multiple code actions, the context needs to be copied somewhere.

Comment (turkeylurkey) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java:45]: Yes, you're right. I think we could just replace it with `context.copy()`. Unfortunately I've seen this code block many times among these quick fixes so I'll go look for other instances.

Comment (turkeylurkey) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java]: No other instances in this pull request.

**Review by evie-lau — APPROVED** [review]

**Review by mrglavas — APPROVED** [review]
