### PR TITLE
Fixed issue#114

### LINKED ISSUE #114: Rename package to "io.openliberty.tools"
On the ls-integration branch(https://github.com/OpenLiberty/liberty-tools-intellij/tree/ls-integration/src/main/java), rename "com.langserver.devtools" to "io.openliberty.tools"

### PR DESCRIPTION
**Pull request by javamultiplex**
closes #114

### CODE REVIEW

File: src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/jaxrs/JaxRsContext.java [hunk 1]
```diff
@@ -87,7 +85,7 @@ public void setRootPath(String rootPath) {
 	public String getApplicationPath() {
 		if (applicationPath == null) {
 			PsiClass applicationPathType = PsiTypeUtils.findType(javaCodeLensContext.getJavaProject(),
-					JAVAX_WS_RS_APPLICATIONPATH_ANNOTATION);
+					JaxRsConstants.JAVAX_WS_RS_APPLICATIONPATH_ANNOTATION);
```
Comment (turkeylurkey) [inline src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/jaxrs/JaxRsContext.java:88]: I see in some cases you remove `import static` and this affects code in the body of the class. Could you restore those imports?

Comment (javamultiplex) [reply src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/jaxrs/JaxRsContext.java]: @turkeylurkey - I have done the changes as suggested. Please review.

**Review by turkeylurkey — APPROVED** [review]
