### PR TITLE
when hover does not provoke a popup, click on pane before trying again

### LINKED ISSUE #374: testDiagnosticAndQuickFixInServerXML() fails - diagnostic popup fails to appear
GradleSingleModLSTest > testDiagnosticAndQuickFixInServerXML() FAILED
    java.util.NoSuchElementException: List is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
        at com.intellij.remoterobot.fixtures.Fixture.findText(Fixture.kt:50)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.chooseQuickFix(UIBotTestUtils.java:940)
        at io.openliberty.tools.intellij.it.SingleModLibertyLSTestCommon.testDiagnosticAndQuickFixInServerXML(SingleModLibertyLSTestCommon.java:273)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)

### PR DESCRIPTION
**Pull request by ajm01**
fixes #374 
fix intermittent failure on the diagnostic - quickfix testcase by clicking on the editor pane if an attempt fails

### CODE REVIEW

File: src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java [hunk 1]
```diff
@@ -687,6 +687,8 @@ public static void hoverInAppServerCfgFile(RemoteRobot remoteRobot, String hover
             } catch (WaitForConditionTimeoutException wftoe) {
                 error = wftoe;
                 TestUtils.sleepAndIgnoreException(2);
+                // click on center of editor pane - allow hover to work on next attempt
```
Comment (mezarin) [inline src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java:690]: The change looks ok, but going back a few lines, line 683, i think the if statement needs a continue if the intent there is to try again. Otherwise, you need to do something with the break on 686. It also seems that the if in question is missing and else or a some code to check for a specific text?

Comment (ajm01) [reply src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java:698]: This method is designed to just raise the hover popup window itself. The main testcase goes on to call additional methods to get the popup text and then validate the popup text. I agree some consolidation would be appropriate, I can do that in a future cleanup issue.

Comment (TrevCraw) [reply src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java:698]: Agreed, we should either be doing some sort of confirmation in `hoverInAppServerCfgFile()` or we should consolidate with `getHoverStringData()`. Let's try to address that in a future PR.

**Review by TrevCraw — APPROVED** [review]
