### PR TITLE
Fix Exception Slow operations are prohibited on EDT

### LINKED ISSUE #674: Fix exception Slow operations are prohibited on EDT
An exception is generated by the LibertyExplorer code because it calls IntelliJ methods known as slow operations. 
```
[   4812] SEVERE - #c.i.u.SlowOperations - Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:101)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.update(FSRecordsImpl.java:718)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findChildInfo(PersistentFSImpl.java:603)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findInPersistence(VirtualDirectoryImpl.java:154)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:137)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:83)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:535)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:51)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.findFileByPath(VfsImplUtil.java:56)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByPath(LocalFileSystemBase.java:119)
	at org.jetbrains.kotlin.idea.gradleJava.scripting.roots.GradleBuildRootKt.loadLastModifiedFiles(GradleBuildRoot.kt:138)
	at org.jetbrains.kotlin.idea.gradleJava.scripting.roots.GradleBuildRootsManager.tryCreateImportedRoot$default(GradleBuildRootsManager.kt:325)
	at org.jetbrains.kotlin.idea.gradleJava.scripting.roots.GradleBuildRootsManager.tryLoadFromFsCache(GradleBuildRootsManager.kt:308)
	at org.jetbrains.kotlin.idea.gradleJava.scripting.roots.GradleBuildRootsManager.loadLinkedRoot(GradleBuildRootsManager.kt:302)
	at org.jetbrains.kotlin.idea.gradleJava.scripting.roots.GradleBuildRootsManager.loadLinkedRoot$default(GradleBuildRootsManager.kt:294)
	at org.jetbrains.kotlin.idea.gradleJava.scripting.ProjectGradleSettingsListener.onProjectsLinked(ProjectGradleSettingsListener.kt:18)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:664)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy4/jdk.proxy4.$Proxy66.onProjectsLinked(Unknown Source)
	at com.intellij.openapi.externalSystem.settings.AbstractExternalSystemSettings.onProjectsLinked(AbstractExternalSystemSettings.java:258)
	at com.intellij.openapi.externalSystem.settings.AbstractExternalSystemSettings$2.lambda$onProjectsLinked$0(AbstractExternalSystemSettings.java:232)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.util.concurrency.CancellationRunnable$run$1.invoke(CancellationRunnable.kt:19)
	at com.intellij.util.concurrency.CancellationRunnable$run$1.invoke(CancellationRunnable.kt:19)
	at com.intellij.util.concurrency.Propagation$runAsCoroutine$deferred$1.invokeSuspend(propagation.kt:195)
	at com.intellij.util.concurrency.Propagation$runAsCoroutine$deferred$1.invoke(propagation.kt)
	at com.intellij.util.concurrency.Propagation$runAsCoroutine$deferred$1.invoke(propagation.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:91)
	at kotlinx.coroutines.BuildersKt.async(Unknown Source)
	at com.intellij.util.concurrency.Propagation.runAsCoroutine(propagation.kt:190)
	at com.intellij.util.concurrency.CancellationRunnable.run(CancellationRunnable.kt:19)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```
One fix was attempted in #590 but this led to another exception, Access is allowed from Event Dispatch Thread (EDT) only:
```
Thread[AWT-EventQueue-0,6,main] 132177491
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 6,4,main] 1324977647 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 132177491
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
	at com.intellij.util.concurrency.ThreadingAssertions.throwThreadAccessException(ThreadingAssertions.java:143)
	at com.intellij.util.concurrency.ThreadingAssertions.assertEventDispatchThread(ThreadingAssertions.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1028)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1340)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1326)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsOnAdd(ActionToolbarImpl.java:356)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:350)
	at java.desktop/java.awt.Container.lambda$addImpl$0(Container.java:1150)
	at java.desktop/sun.awt.SunToolkit.lambda$performWithTreeLock$1(SunToolkit.java:2145)
	at java.desktop/sun.awt.SunToolkit.performOnMainThreadIfNeeded(SunToolkit.java:2170)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2143)
	at java.desktop/java.awt.Container.addImpl(Container.java:1104)
	at java.desktop/java.awt.Container.add(Container.java:1001)
	at com.intellij.openapi.ui.SimpleToolWindowPanel.setToolbar(SimpleToolWindowPanel.java:111)
	at io.openliberty.tools.intellij.LibertyExplorer.lambda$new$1(LibertyExplorer.java:71)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### PR DESCRIPTION
**Pull request by vaisakhkannan**
Fixes #674 
Fixed Exception Slow operations are prohibited on EDT

### CODE REVIEW

**Review by anusreelakshmi934 — DISMISSED** [review]
Looks Good for me

File: src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java [hunk 1]
```diff
@@ -48,23 +51,37 @@ public class LibertyExplorer extends SimpleToolWindowPanel {
 
     public LibertyExplorer(@NotNull Project project) {
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java:52]: Constructors normally complete their initialization synchronously, allowing the creator of that object to reliably read the initial state of the object. With this change which dispatching the initialization on to other threads, the constructor can (and likely will return) before either the content or toolbar is set. With the inner calls to `invokeLater()` it seems the content and toolbar could be set in any order. Did you verify that no users of this object assume that these fields have been set within the constructor? A demo which shows this working would help.

File: src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java [hunk 2]
```diff
@@ -48,23 +51,37 @@ public class LibertyExplorer extends SimpleToolWindowPanel {
...
-            jbTextArea.setEditable(false);
-            jbTextArea.setBackground(getBackground());
-            jbTextArea.setLineWrap(true);
-
-            this.setContent(jbTextArea);
-        }
-        ActionToolbar actionToolbar = buildActionToolbar(tree);
-        this.setToolbar(actionToolbar.getComponent());
+        ModalityState modalityState = getModalityState();
+        ApplicationManager.getApplication().executeOnPooledThread(() -> {
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java:55]: It would be a good idea to add some documentation here which describes the problem being solved and the solution, in particular if this was suggested by JetBrains documentation or some other source it would be helpful to provide a link to that guidance.

**Review by mrglavas — CHANGES_REQUESTED** [review]
See review comments.

File: src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java (hunk 1 above)
Comment (vaisakhkannan) [reply src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java:52]: I will conduct the demo today to demonstrate the functionality, after which we can finalize

File: src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java (hunk 2 above)
Comment (vaisakhkannan) [reply src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java:55]: I will add documentation as comments. Jetbrains Documentation link https://plugins.jetbrains.com/docs/intellij/general-threading-rules.html that I referred

File: src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java (hunk 1 above)
Comment (mrglavas) [reply src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java:52]: Thanks for the demo today. It certainly appears things are working as expected.

File: src/test/resources/ci/scripts/run.sh [hunk 3]
```diff
@@ -155,7 +155,7 @@ main() {
 
     # Start the IDE.
     echo -e "\n$(${currentTime[@]}): INFO: Starting the IntelliJ IDE..."
-    ./gradlew -Dide.slow.operations.assertion=false runIdeForUiTests --info  > remoteServer.log  2>&1 &
```
[the remark this answers is not in the document]
Comment (vaisakhkannan) [reply src/test/resources/ci/scripts/run.sh:158]: Paul actually made a change to this in PR https://github.com/OpenLiberty/liberty-tools-intellij/pull/673/files as part of issue 590. Therefore, at the time, he might faced the slow operation exception, perhaps that was the reason he added this change in order to avoid getting exceptions during UI testing.

So, I made a change to the initial state with the default value:

`./gradlew runIdeForUiTests --info > remoteServer.log 2>&1 &`
@turkeylurkey , could you please confirm if this change is okay with the modifications I made?

File: src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java (hunk 1 above)
Comment (mrglavas) [reply src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java:52]: @vaisakhkannan Thanks for verifying.

File: src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java (hunk 2 above)
Comment (mrglavas) [reply src/main/java/io/openliberty/tools/intellij/LibertyExplorer.java:57]: Looks good now. Thanks.

**Review by mrglavas — APPROVED** [review]
