### PR TITLE
Fixes #534: Refactored quick fixes and test cases for RemoveParamsProposal

### LINKED ISSUE #534: Transform the Quick Fixes which use RemoveParamsProposal to implement the code action participant extension point.
See the initial work completed here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/313.

In addition to refactoring the code, the code action participants will need to be added to the plugin.xml and the relevant Jakarta EE code action tests should be enabled.

### PR DESCRIPTION
**Pull request by dessina-devasia**
Fixes #534 
Refactored quick fixes and test cases for RemoveParamsProposal

### CODE REVIEW

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/RemoveElementsProposal.java [hunk 1]
```diff
@@ -41,10 +43,23 @@ protected RemoveElementsProposal(String label, PsiFile sourceCU, PsiFile invocat
...
 
+    protected RemoveElementsProposal(String label, PsiFile sourceCU, PsiFile invocationNode,
+                                     PsiModifierListOwner binding, int relevance,
+                                     List<? extends PsiElement> elementsToRemove, boolean isFormatRequired) {
+        super(label, CodeActionKind.QuickFix, relevance);
+        this.sourceCU = sourceCU;
+        this.invocationNode = invocationNode;
+        this.binding = binding;
+        this.elementsToRemove = elementsToRemove;
+        this.isFormatRequired =isFormatRequired;
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/RemoveElementsProposal.java:54]: Formatting :-) Should have consistent spacing throughout the source file.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java [hunk 2]
```diff
@@ -35,54 +44,96 @@
...
+        assert parentMethod != null;
+        final PsiParameterList parameterList = parentMethod.getParameterList();
+        final List<PsiParameter> entityParams = new ArrayList<>();
+        String title = toResolve.getTitle();
+
+        if (parameterList.getParametersCount() > 0) {
+            final PsiParameter[] parameters = parameterList.getParameters();
+            for (PsiParameter parameter : parameters) {
+                if (isEntityParam(parameter)) {
+                    if (!title.contains(parameter.getName())) {
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java:120]: contains() isn't going to work in general. What if the parameter name is one of the other words in the title or is contained in the name of another parameter? This was checking indexes before. I think the list should have been pre-computed and saved in the CodeAction. See `io.openliberty.tools.intellij.lsp4mp4ij.psi.core.java.codeaction.InsertAnnotationMissingQuickFix` as an example of saving extended data.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/RemoveElementsProposal.java (hunk 1 above)
Comment (dessina-devasia) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/RemoveElementsProposal.java]: Modifications done. Please have a look.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java (hunk 2 above)
Comment (dessina-devasia) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java]: Modifications done. Please have a look.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java [hunk 3]
```diff
@@ -155,4 +148,19 @@ private boolean isEntityParam(PsiParameter param) {
...
+        codeAction.setDiagnostics(Collections.singletonList(diagnostic));
+        codeAction.setKind(CodeActionKind.QuickFix);
+        Map<String, Object> extendedData = new HashMap<>();
+        extendedData.put(ENTITY_PARAM_INDEX_KEY, entityParamIndex);
+        codeAction.setData(new CodeActionResolveData(context.getUri(), participantId,
+                context.getParams().getRange(), extendedData,
+                context.getParams().isResourceOperationSupported(),
+                context.getParams().isCommandConfigurationUpdateSupported()));
+        return codeAction;
+    }
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java:165]: This method is mostly a copy of `JDTUtils.createCodeAction()` with the main difference being the addition of the HashMap. Seems like a more generalized version belongs in `JDTUtils` and should be called from here instead of duplicating the code again.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java [hunk 4]
```diff
@@ -47,6 +43,8 @@
 public class ResourceMethodMultipleEntityParamsQuickFix implements IJavaCodeActionParticipant {
 
     private static final Logger LOGGER = Logger.getLogger(ResourceMethodMultipleEntityParamsQuickFix.class.getName());
+    private static final String ENTITY_PARAM_INDEX_KEY = "entityParamIndex";
+    private final List<Integer> entityParamIndexes = new ArrayList<>();
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java:47]: Each `IJavaCodeActionParticipant` is a singleton. It is not safe to store transient data for a specific code action in this object. Think about what may happen if there are multiple diagnostics that have the same quick fix (e.g. threads that might be simultaneously reading/writing to this object) or what might happen if resolveCodeAction() isn't called immediately after getCodeAction(). Also looks like the field is never cleared, so would leak memory over time. I believe this list should also be stored in the HashMap and carried along with the rest of the `CodeActionResolveData`.

**Comment by mrglavas** [comment]
On the most recent build I see that `PostConstructAnnotationTest` is failing on all platforms. Will need to resolve this before this PR can be merged.

**Review by mrglavas — CHANGES_REQUESTED** [review]
See comments for requested changes.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java (hunk 3 above)
Comment (dessina-devasia) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java]: Modification done

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java (hunk 4 above)
Comment (dessina-devasia) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/jax_rs/ResourceMethodMultipleEntityParamsQuickFix.java]: Modification done

**Review by vaisakhkannan — APPROVED** [review]
Looks good to me

**Review by mrglavas — DISMISSED** [review]
Verified that my previous comments were addressed. Looks good. Thanks.

**Review by anusreelakshmi934 — APPROVED** [review]

**Review by mrglavas — APPROVED** [review]
