### PR TITLE
Terminate the process running the IDE if it crashes

### LINKED ISSUE #1122: Mac automated UI test failure: SocketTimeoutException, terminate IDE
The UI robot is trying to type characters into the editor but the editor process is not confirming the characters.
```
GradleSingleModJakartaLSTest > testJakartaQuickFixInJavaPart() FAILED
    java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at okio.InputStreamSource.read(JvmOkio.kt:94)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
        at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
        ...
```
Once we have detected this exception we should terminate the IDE since it is no longer responsive.

### PR DESCRIPTION
**Pull request by turkeylurkey**
Fixes #1122

Fix to detect the process id on Windows. I use `kill -1` and `kill -9` and `sleep 5` in an attempt to avoid the defunct process I've seen in the past.

Log showing how the Windows code works for those not familiar with Windows:
```
+ '[' 23 -eq 23 ']'
+ [[ MINGW64_NT-10.0-20348 == \M\I\N\G\W\6\4\_\N\T* ]]
+ kill -n 1 1823
+ sleep 5
./src/test/resources/ci/scripts/run.sh: line 195:  1823 Hangup                  ./gradlew runIdeForUiTests -PuseLocal=$USE_LOCAL_PLUGIN --info > remoteServer.log 2>&1
+ kill -n 9 1823
./src/test/resources/ci/scripts/run.sh: line 209: kill: (1823) - No such process
+ sleep 5
+ ps -ef
     UID     PID    PPID  TTY        STIME COMMAND
runnerad    1869    1716 ?        00:08:10 /usr/bin/ps
runnerad    1716       1 ?        23:48:37 /usr/bin/bash
```
Log from Mac (largely the same as Linux)
```
+ '[' 23 -eq 23 ']'
+ [[ Darwin == \M\I\N\G\W\6\4\_\N\T* ]]
+ kill -1 9176
+ sleep 5
+ kill -9 9176
./src/test/resources/ci/scripts/run.sh: line 215: kill: (9176) - No such process
+ sleep 5
+ ps -f 9176
  UID   PID  PPID   C STIME   TTY           TIME CMD
```
Another log from Mac where it appears the `kill -1` did not work
```
+ '[' 23 -eq 23 ']'
+ [[ Darwin == \M\I\N\G\W\6\4\_\N\T* ]]
+ kill -1 9412
+ sleep 5
+ kill -9 9412
+ sleep 5
+ ps -f 9412
  UID   PID  PPID   C STIME   TTY           TIME CMD
```

### CODE REVIEW

File: src/test/java/io/openliberty/tools/intellij/it/TestUtils.java [hunk 1]
```diff
@@ -576,7 +576,7 @@ public static void copyDirectory(String sourceDirectoryLocation, String destinat
      * This searches the output of this JUnit run for SocketTimeoutException which
      * has been identified as a fatal error and occurs during the Mac tests.
      */
-    public static synchronized void detectFatalError() {
+    public static void detectFatalError() {
```
Comment (mrglavas) [inline src/test/java/io/openliberty/tools/intellij/it/TestUtils.java:579]: FYI to other reviewers. This is a response to my comment from a previous PR where after other changes were made, `synchronized` is no longer required on this method.

**Review by vaisakhkannan — APPROVED** [review]
looks good to me, Thanks @turkeylurkey

File: src/test/java/io/openliberty/tools/intellij/it/TestUtils.java (hunk 1 above)
Comment (turkeylurkey) [reply src/test/java/io/openliberty/tools/intellij/it/TestUtils.java:579]: Thank you!
