### PR TITLE
Fixes issue #1522: Sync up from lsp4jakarta to show all valid diagnostics for constraint annotations at once

### LINKED ISSUE #1522: Sync up from lsp4jakarta to show all valid diagnostics for constraint annotations at once
lsp4jakarta PR: https://github.com/eclipse-lsp4jakarta/lsp4jakarta/pull/806
lsp4jakarta issue: https://github.com/eclipse-lsp4jakarta/lsp4jakarta/issues/523

### PR DESCRIPTION
**Pull request by archana-1924**
Fixes #1522 
lsp4jakarta PR: https://github.com/eclipse-lsp4jakarta/lsp4jakarta/pull/806
lsp4jakarta issue: https://github.com/eclipse-lsp4jakarta/lsp4jakarta/issues/523

### CODE REVIEW

**Comment by archana-1924** [comment]
https://github.com/user-attachments/assets/814ecd8c-a548-4528-84e6-316f102c7378

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationDiagnosticsCollector.java [hunk 1]
```diff
@@ -156,13 +153,15 @@ private void validAnnotation(PsiElement element, PsiAnnotation annotation, Strin
...
-                } else if (matchedAnnotation.equals(NOT_EMPTY) || matchedAnnotation.equals(SIZE)) {
+                }
+                case NOT_EMPTY, SIZE -> {
                     if (!(isSizeOrNonEmptyAllowed(type))) {
                         String source = getSource(isMethod, isField, annotationName, "SizeOrNonEmptyAnnotations");
                         diagnostics.add(createDiagnostic(element, (PsiJavaFile) element.getContainingFile(),
                                 source, DIAGNOSTIC_CODE_INVALID_TYPE, annotationName, DiagnosticSeverity.Error));
                     }
                 }
+                default -> System.out.println("Unexpected value for annotation");
```
Comment (venmanyarun) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationDiagnosticsCollector.java]: use logger

**Review by venmanyarun — CHANGES_REQUESTED** [review]

**Review by venmanyarun — APPROVED** [review]

**Review by Rejoice472 — APPROVED** [review]

**Review by turkeylurkey — APPROVED** [review]
I don't know if I missed something but it looks like most of this code is just a rewrite of the IF statements. Please don't reformat or rewrite code for style, it makes reviewing harder.

**Comment by archana-1924** [comment]
> I don't know if I missed something but it looks like most of this code is just a rewrite of the IF statements. Please don't reformat or rewrite code for style, it makes reviewing harder.

Sure, I understand how it could make the review harder, aim was to first fix the issue itself and hopefully refactor the existing code to perform better. Will keep in mind going forward.
