### PR TITLE
Fixes #631 - Modified build path

### LINKED ISSUE #631: Invalid input to URL constructor
Found in the IntelliJ output during testing. Need to investigate how to turn a file into a url.
```
2024-01-30 06:48:23,160 [2351960]   WARN - #io.openliberty.tools.intellij.runConfiguration.LibertyRunManagerListener - Unable to clear custom start parameters for Liberty run configuration associated with: /home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/gradle/singleModGradleMP/build.gradle. Could not resolve build file.
java.net.MalformedURLException: no protocol: /home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/gradle/singleModGradleMP/build.gradle
	at java.base/java.net.URL.<init>(URL.java:674)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at io.openliberty.tools.intellij.runConfiguration.LibertyRunManagerListener.runConfigurationRemoved(LibertyRunManagerListener.java:42)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:699)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:659)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:422)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:401)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:460)
	at jdk.proxy2/jdk.proxy2.$Proxy106.runConfigurationRemoved(Unknown Source)
	at
```

Also as part of this issue, write a unit or integration test to cover this scenario.

### PR DESCRIPTION
**Pull request by anusreelakshmi934**
Fixes #631

### CODE REVIEW

**Review by turkeylurkey — COMMENTED** [review]
It is usually best not to hard code strings like this. Looking at other locations where getBuildFile() is used I found this line. It is better because it builds the file using tools: `            VirtualFile vBuildFile = VfsUtil.findFile(Paths.get(runConfig.getBuildFile()), true);`

File: src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java
Comment (vaisakhkannan) [inline src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java:1]: Update year in header as  -->    2020, 2024

File: src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java
Comment (vaisakhkannan) [inline src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java:1]: Update year in header as --> 2023, 2024

File: src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPProjectTest.java
Comment (vaisakhkannan) [inline src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPProjectTest.java:1]: Update year in header as --> 2023, 2024

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java
Comment (vaisakhkannan) [inline src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:1]: Update year in header as --> 2023, 2024

**Review by vaisakhkannan — CHANGES_REQUESTED** [review]
Please do the requested changes

**Comment by anusreelakshmi934** [comment]
I conducted the test without implementing the fix and confirmed that it fails. Additionally, the current failure on Mac is unrelated to the recent change; it's a known issue.

**Comment by TrevCraw** [comment]
Notes from PR demo:
1. Change the return type and name for getWLPPath() method.
2. Move the action of reading the debug port from server.env into a common method under TestUtils.
3. Check the debug port value in server.env after Liberty custom start with the debugPort parameter.

File: src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java [hunk 1]
```diff
@@ -88,6 +96,22 @@ public String getWLPInstallPath() {
...
+     * Then, it expands the nodes corresponding to the given path within the project tree.
+     *
+     * @return JTreeFixture representing the expanded project tree nodes.
+     */
+    @Override
+    public JTreeFixture expandProjectTreeNodes() {
+        // get a JTreeFixture reference to the file project viewer entry
+        ProjectFrameFixture projectFrame = remoteRobot.find(ProjectFrameFixture.class, Duration.ofMinutes(2));
+        JTreeFixture projTree = projectFrame.getProjectViewJTree(getSmMPProjectName());
+        UIBotTestUtils.openFile(remoteRobot, getSmMPProjectName(), "server.env", getSmMPProjectName(), "build", "wlp", "usr", "servers", "defaultServer");
```
Comment (aparnamichael) [inline src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java:111]: Can we use this method to expand any node in the project tree by passing file name and path.

File: src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java [hunk 2]
```diff
@@ -88,6 +96,22 @@ public String getWLPInstallPath() {
...
 
+    /**
+     * This method expands specific nodes within a project tree represented by a JTreeFixture.
+     * It locates the ProjectFrameFixture using a remote robot and retrieves a JTreeFixture for the project view.
+     * Then, it expands the nodes corresponding to the given path within the project tree.
+     *
+     * @return JTreeFixture representing the expanded project tree nodes.
+     */
+    @Override
+    public JTreeFixture expandProjectTreeNodes() {
```
Comment (aparnamichael) [inline src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java:107]: We are not using the returned value, so we can make the return type to void.

File: src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java (hunk 1 above)
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java]: Removed the newly created method. Used UIBotTestUtils.openFile to open the server.env file by specifying paths seperately for maven and gradle files.

File: src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java (hunk 2 above)
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java]: Removed this method to implement it in another way

File: src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java [hunk 3]
```diff
@@ -88,6 +93,16 @@ public String getWLPInstallPath() {
         return WLP_INSTALL_PATH;
     }
 
+    /**
+     * Returns the path of server.env file.
+     *
+     * @return The path of server.env file.
+     */
+    @Override
+    public String[] getWLPServerPath() {
```
Comment (aparnamichael) [inline src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java:102]: Give more meaningful name.

Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/GradleSingleModMPProjectTest.java]: Changed the method name to getServerEnvPath()

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java [hunk 4]
```diff
@@ -923,6 +924,78 @@ public static void prepareEnv(String projectPath, String projectName) {
...
+
+        } catch (IOException e) {
+            System.err.println("Error reading the file: " + e.getMessage());
+
+        } finally {
+            cleanupAndStopServerIfNeeded(absoluteWLPPath);
+        }
+    }
+
+    private void cleanupAndStopServerIfNeeded(String absoluteWLPPath) {
```
Comment (aparnamichael) [inline src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:985]: Can we move this method to utils or some common classes, so that we can reuse this method in other tests.

Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java]: Moved cleanupAndStopServerIfNeeded into UIBotTestUtils.

**Comment by aparnamichael** [comment]
Looks good to me.

**Review by aparnamichael — APPROVED** [review]

**Review by vaisakhkannan — APPROVED** [review]
Looks good, Thanks

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java [hunk 5]
```diff
@@ -923,6 +924,69 @@ public static void prepareEnv(String projectPath, String projectName) {
...
+        } finally {
+            // Stops the Liberty server if necessary.
+            UIBotTestUtils.cleanupAndStopServerIfNeeded(remoteRobot, absoluteWLPPath, getSmMPProjectName(), testName);
+        }
+
+        // Cleanup configurations.
+        UIBotTestUtils.deleteLibertyRunConfigurations(remoteRobot);
+
+        // Start dev mode.
+        UIBotTestUtils.runLibertyActionFromLTWDropDownMenu(remoteRobot, "Start", true, 3);
```
Comment (TrevCraw) [inline src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:968]: Is there a reason why the `usePlayButton` boolean param is set to `true` here and set to `false` in the first call (line 941)?

File: src/test/java/io/openliberty/tools/intellij/it/TestUtils.java [hunk 6]
```diff
@@ -523,4 +523,34 @@ public static boolean isServerStopNeeded(String wlpInstallPath) {
...
+        boolean debugPortIsDefault = lines.stream().anyMatch(line -> line.contains("WLP_DEBUG_ADDRESS=7777"));
+        Assertions.assertTrue(debugPortIsDefault, "Debug Port is not default");
+    }
+
+    /**
+     * Reads the server.env file to check if the debug port is set to the specified custom value.
+     *
+     * @param absoluteWLPPath The absolute path to the WLP directory.
+     */
+    public static void checkCustomDebugPort(String absoluteWLPPath) throws IOException {
```
Comment (TrevCraw) [inline src/test/java/io/openliberty/tools/intellij/it/TestUtils.java:547]: `checkCustomDebugPort` and `checkDefaultDebugPort` are essentially the same method with one difference. Please write one method to handle both the default and custom scenarios.

File: src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java [hunk 7]
```diff
@@ -2406,4 +2410,26 @@ public static void closeErrorDialog(RemoteRobot remoteRobot) {
...
+     *
+     * @param remoteRobot       The RemoteRobot instance.
+     * @param absoluteWLPPath   The absolute path of the Liberty installation.
+     * @param projectName       The name of the project to select.
+     * @param testName          The name of the test calling this method.
+     */
+    public static void cleanupAndStopServerIfNeeded(RemoteRobot remoteRobot, String absoluteWLPPath, String projectName, String testName) {
+
+        // Open the terminal window.
+        openTerminalWindow(remoteRobot);
```
Comment (TrevCraw) [inline src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java:2425]: why do we need to open the terminal window here?

File: src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java [hunk 8]
```diff
@@ -2406,4 +2410,26 @@ public static void closeErrorDialog(RemoteRobot remoteRobot) {
...
+
+        if (TestUtils.isServerStopNeeded(absoluteWLPPath)) {
+            // Sleep for a few seconds to allow dev mode to finish running the tests.
+            TestUtils.sleepAndIgnoreException(60);
```
Comment (TrevCraw) [inline src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java:2429]: dev mode is not running any tests in this scenario, so there is no need for the sleep.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java [hunk 9]
```diff
@@ -923,6 +924,69 @@ public static void prepareEnv(String projectPath, String projectName) {
...
+
+        // Run the configuration dialog.
+        UIBotTestUtils.runStartParamsConfigDialog(remoteRobot, getStartParamsDebugPort());
+
+        try {
+            // Validate that the project started.
+            TestUtils.validateProjectStarted(testName, getSmMpProjResURI(), getSmMpProjPort(), getSmMPProjOutput(), absoluteWLPPath, false);
+
+            // Expand the Project tree and open server.env file
+            UIBotTestUtils.openFile(remoteRobot, getSmMPProjectName(), "server.env", getServerEnvPath());
```
Comment (TrevCraw) [inline src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:951]: What is the reason we need to open the `server.env` file in the editor?

**Review by TrevCraw — CHANGES_REQUESTED** [review]

File: src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPProjectTest.java [hunk 10]
```diff
@@ -96,6 +111,16 @@ public String getWLPInstallPath() {
...
     }
 
+    /**
+     * Returns the path of server.env file.
+     *
+     * @return The path of server.env file.
+     */
+    @Override
+    public String[] getServerEnvPath() {
+        return new String[]{SM_MP_PROJECT_NAME, TARGET_DIR, LIBERTY_DIR, "wlp", "usr", "servers", "defaultServer", "server.env"};
```
[the remark this answers is not in the document]
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPProjectTest.java:121]: When using `WLP_INSTALL_PATH` we are getting `Paths.get("target", "liberty").toString();` which gives us `target/liberty`. For the function to open the required file we need to get `target, liberty`. So using `WLP_INSTALL_PATH` was not possible. But in the case of Gradle there doesnt seem to be a problem because the value of `WLP_INSTALL_PATH` is `build`.

File: src/test/java/io/openliberty/tools/intellij/it/TestUtils.java (hunk 6 above)
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/TestUtils.java:547]: Changed into a single method that handles both scenarios by passing the debug port as an argument.

File: src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java (hunk 7 above)
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java:2425]: Since the openFile method has `hideTerminalWindow(remoteRobot);`, the terminal window gets minimised while reading the server.env file. So inorder to bring it back to the frame, i added the open terminal window method there.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java (hunk 9 above)
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:951]: We need to read the server.env file and check for the debug port value.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java (hunk 5 above)
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:968]: We can use both true or false, that is if play button should be used to run the action or not. I have changed both to true.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java [hunk 11]
```diff
@@ -967,6 +1031,13 @@ public static void prepareEnv(String projectPath, String projectName) {
      */
     public abstract String getWLPInstallPath();
 
+    /**
+     * Returns the path of server.env file.
+     *
+     * @return The path of server.env file.
+     */
+    public abstract String[] getServerEnvPath();
```
[the remark this answers is not in the document]
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:1039]: Renamed to getWLPServerEnvPath()

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java (hunk 9 above)
Comment (TrevCraw) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java]: We are using the Java Files library to read the `server.env` file in `checkDebugPort()`. There is no connection between using that library and what is open in the IntelliJ editor.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java]: This is no longer necessary as we're only reading the server.env file instead of opening it.

File: src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPProjectTest.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/MavenSingleModMPProjectTest.java]: This is also no longer necessary as we're only reading the server.env file instead of opening it.

File: src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java (hunk 7 above)
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java]: Removed the method `cleanupAndStopServerIfNeeded` from UIBotTestUtils.java. Just added the method to `runStopAction` only in `testCustomStartParametersClearedOnConfigRemoval` method itself.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java (hunk 9 above)
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java]: Removed the openFile method. We are only reading the server.env file instead of opening it.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java [hunk 12]
```diff
@@ -923,6 +924,69 @@ public static void prepareEnv(String projectPath, String projectName) {
...
+
+        try {
+            // Validate that the project started.
+            TestUtils.validateProjectStarted(testName, getSmMpProjResURI(), getSmMpProjPort(), getSmMPProjOutput(), absoluteWLPPath, false);
+
+            // To check if debug port is set to a custom value (e.g., 9876)
+            TestUtils.checkDebugPort(absoluteWLPPath, 9876);
+
+        } catch (IOException e) {
+            System.err.println("Error reading the file: " + e.getMessage());
```
Comment (TrevCraw) [inline src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:954]:
```suggestion
            System.err.println("Error reading the server.env file: " + e.getMessage());
```

Comment (TrevCraw) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:954]: Instead of a print line statement, we should fail the test if we cannot read the `server.env`. You can use `Assertions.fail()`.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java [hunk 13]
```diff
@@ -923,6 +924,69 @@ public static void prepareEnv(String projectPath, String projectName) {
...
+
+        try {
+            // Validate that the project started.
+            TestUtils.validateProjectStarted(testName, getSmMpProjResURI(), getSmMpProjPort(), getSmMPProjOutput(), absoluteWLPPath, false);
+
+            // To check if debug port is set to the default value (7777)
+            TestUtils.checkDebugPort(absoluteWLPPath, 7777);
+
+        } catch (IOException e) {
+            System.err.println("Error reading the file: " + e.getMessage());
```
Comment (TrevCraw) [inline src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:978]: same as above, we should use `Assertions.fail()` and specify the `server.env` file

**Review by TrevCraw — CHANGES_REQUESTED** [review]
Please address the new comments. 

And did you confirm that `testCustomStartParametersClearedOnConfigRemoval()` still fails when the fix is removed?

**Comment by anusreelakshmi934** [comment]
> Please address the new comments.
> 
> And did you confirm that `testCustomStartParametersClearedOnConfigRemoval()` still fails when the fix is removed?

Yes. It fails without the fix

File: src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java [hunk 14]
```diff
@@ -629,6 +629,10 @@ public static void openFile(RemoteRobot remoteRobot, String projectName, String
 
                 projTree.expand(filePath);
 
+                // Awaiting the full expansion of the project tree to ensure that it correctly selects the server.env file.
+                // We need to seek a more effective solution for this in the future.
+                TestUtils.sleepAndIgnoreException(5);
```
[the remark this answers is not in the document]
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java:634]: No. we no longer need this. I have removed it.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java (hunk 13 above)
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:978]: Changed to Assertions.fail()

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java (hunk 12 above)
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:954]: > Instead of a print line statement, we should fail the test if we cannot read the `server.env`. You can use `Assertions.fail()`.

Changed to Assertions.fail()

**Review by TrevCraw — APPROVED** [review]

**Review by aparnamichael — APPROVED** [review]
