### PR TITLE
Get back to the Welcome screen at start up of UI test

### LINKED ISSUE #1124: Mac automated UI test failure: SocketTimeoutException, restart testing on new environment
The UI robot is trying to type characters into the editor but the editor process is not confirming the characters.
```
GradleSingleModJakartaLSTest > testJakartaQuickFixInJavaPart() FAILED
    java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at okio.InputStreamSource.read(JvmOkio.kt:94)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
        at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
        ...
```
Start testing on the IDE after restart.

The challenge is that when you restart the IDE it reloads the project that was in use when the IDE last crashed. We need to close that project and get back to the Welcome screen so that the test can load the project that is required (typically the project for the first test since we are starting testing over from the beginning).

### PR DESCRIPTION
**Pull request by turkeylurkey**
Fixes #1124 

Introduce a new method to find the Welcome screen of IntelliJ. This is needed when we start IntelliJ after a crash. In this case IntelliJ will start and load the last project that was used. This is not expected by the UI robot because it always closes files and projects after each test. So the fix is to close all files and lose the current project to get back to the Welcome screen when we detect that the Welcome screen is not up. 

I also noticed that there were some unused imports so I did a sweep through all the files in the directory and updated the copyrights, removed unused imports and also extra blank lines.

### CODE REVIEW

**Comment by turkeylurkey** [comment]
Test results for Mac. 5 failures. The first 4 were similar but not the same. The first two were the same. The second two were the same.
```
1. 

GradleSingleModMPLSTest > testDiagnosticInMicroProfileConfigProperties() STANDARD_OUT
    INFO: 2024-11-26T *22:32:28* .920738: GradleSingleModMPLSTest.testDiagnosticInMicroProfileConfigProperties(). Entry
    Type mismatch: boolean expected. By default, this value will be interpreted as 'false'
     microprofile (value)
    INFO: 2024-11-26T22:34:42.550085: GradleSingleModMPLSTest.testDiagnosticInMicroProfileConfigProperties(). Exit

GradleSingleModMPLSTest > testDiagnosticInMicroProfileConfigProperties() FAILED
    java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
        at java.base/sun.nio.ch
...
        at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getActionMenu(ProjectFrameFixture.java:66)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.pasteOnActiveWindow(UIBotTestUtils.java:1509)
        at io.openliberty.tools.intellij.it.SingleModMPLSTestCommon.testDiagnosticInMicroProfileConfigProperties(SingleModMPLSTestCommon.java:275)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


2. 

GradleSingleModMPLSTest > testDiagnosticInMicroProfileConfigProperties() STANDARD_OUT
    INFO: 2024-11-26T *23:32:32* .363554: GradleSingleModMPLSTest.testDiagnosticInMicroProfileConfigProperties(). Entry
    Type mismatch: boolean expected. By default, this value will be interpreted as 'false'
     microprofile (value)
    INFO: 2024-11-26T23:34:29.664765: GradleSingleModMPLSTest.testDiagnosticInMicroProfileConfigProperties(). Exit

GradleSingleModMPLSTest > testDiagnosticInMicroProfileConfigProperties() FAILED
    java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
   ...
        at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getActionMenu(ProjectFrameFixture.java:66)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.pasteOnActiveWindow(UIBotTestUtils.java:1509)
        at io.openliberty.tools.intellij.it.SingleModMPLSTestCommon.testDiagnosticInMicroProfileConfigProperties(SingleModMPLSTestCommon.java:275)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


3. 

GradleSingleModMPLSTest > testQuickFixInMicroProfileConfigProperties() STANDARD_OUT
    INFO: 2024-11-27T *00:26:31* .660308: GradleSingleModMPLSTest.testQuickFixInMicroProfileConfigProperties(). Entry
    INFO: 2024-11-27T00:28:11.785347: GradleSingleModMPLSTest.testQuickFixInMicroProfileConfigProperties(). Exit

GradleSingleModMPLSTest > testQuickFixInMicroProfileConfigProperties() FAILED
    java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
 ...
        at com.intellij.remoterobot.RemoteRobot.isMac(RemoteRobot.kt:61)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.goToLineAndColumn(UIBotTestUtils.java:1357)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.pasteOnActiveWindow(UIBotTestUtils.java:1491)
        at io.openliberty.tools.intellij.it.SingleModMPLSTestCommon.testQuickFixInMicroProfileConfigProperties(SingleModMPLSTestCommon.java:313)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


 4. 

 GradleSingleModMPLSTest > testQuickFixInMicroProfileConfigProperties() STANDARD_OUT
    INFO: 2024-11-27T *01:24:22* .454579: GradleSingleModMPLSTest.testQuickFixInMicroProfileConfigProperties(). Entry
    INFO: 2024-11-27T01:26:07.610941: GradleSingleModMPLSTest.testQuickFixInMicroProfileConfigProperties(). Exit

GradleSingleModMPLSTest > testQuickFixInMicroProfileConfigProperties() FAILED
    java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at okio.InputStreamSource.read(JvmOkio.kt:93)
 ...
        at com.intellij.remoterobot.RemoteRobot.isMac(RemoteRobot.kt:61)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.goToLineAndColumn(UIBotTestUtils.java:1357)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.pasteOnActiveWindow(UIBotTestUtils.java:1491)
        at io.openliberty.tools.intellij.it.SingleModMPLSTestCommon.testQuickFixInMicroProfileConfigProperties(SingleModMPLSTestCommon.java:313)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 

5. 

JakartaWebSocketTest > addPathParamsAnnotation STANDARD_ERROR
    [ 938755]   WARN - #o.j.i.maven - updateAllMavenProjects started: incremental=true, MavenProjectsManagerEx.addManagedFilesWithProfilesAndUpdate addPathParamsAnnotation
    [ 938775]   WARN - #o.j.i.maven - ImportLogging. pomReadingStarted (1)
    [ 940468]   WARN - #o.j.i.maven - ImportLogging. pomReadingFinished (1)
    [ 945510]   WARN - #o.j.i.maven - ImportLogging. importStarted (1)
    [ 945528]   WARN - #o.j.i.maven - Can't migrate the project to external project files storage: Project.isExternalStorageEnabled=false
    [ 945860]   WARN - #o.j.i.maven - ImportLogging. importFinished (1): 1, 1
    [ 945866]   WARN - #o.j.i.maven - ImportLogging. pluginResolutionStarted (1)
    [ 945867]   WARN - #o.j.i.maven - ImportLogging. pluginResolutionFinished (1)
    [ 945869]   WARN - #o.j.i.maven - updateAllMavenProjects finished: incremental=true, MavenProjectsManagerEx.addManagedFilesWithProfilesAndUpdate addPathParamsAnnotation

GradleSingleModJakartaLSTest > initializationError FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'ComponentFixture' by '//div[@class='ActionMenu' and @text='Window']//div[@class='ActionMenu' and @text='Editor Tabs']' in 10s) 
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
        at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getChildActionMenu(ProjectFrameFixture.java:98)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.closeAllEditorTabs(UIBotTestUtils.java:749)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.findWelcomeFrame(UIBotTestUtils.java:2543)
        at io.openliberty.tools.intellij.it.SingleModJakartaLSTestCommon.prepareEnv(SingleModJakartaLSTestCommon.java:186)
        at io.openliberty.tools.intellij.it.GradleSingleModJakartaLSTest.setup(GradleSingleModJakartaLSTest.java:40)

GradleSingleModLSTest > initializationError FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'ComponentFixture' by '//div[@class='ActionMenu' and @text='Window']//div[@class='ActionMenu' and @text='Editor Tabs']' in 10s) 
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
        at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getChildActionMenu(ProjectFrameFixture.java:98)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.closeAllEditorTabs(UIBotTestUtils.java:749)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.findWelcomeFrame(UIBotTestUtils.java:2543)
        at io.openliberty.tools.intellij.it.SingleModLibertyLSTestCommon.prepareEnv(SingleModLibertyLSTestCommon.java:398)
        at io.openliberty.tools.intellij.it.GradleSingleModLSTest.setup(GradleSingleModLSTest.java:40)

GradleSingleModMPLSTest > initializationError FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'ComponentFixture' by '//div[@class='ActionMenu' and @text='Window']//div[@class='ActionMenu' and @text='Editor Tabs']' in 10s) 
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
        at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getChildActionMenu(ProjectFrameFixture.java:98)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.closeAllEditorTabs(UIBotTestUtils.java:749)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.findWelcomeFrame(UIBotTestUtils.java:2543)
        at io.openliberty.tools.intellij.it.SingleModMPLSTestCommon.prepareEnv(SingleModMPLSTestCommon.java:327)
        at io.openliberty.tools.intellij.it.GradleSingleModMPLSTest.setup(GradleSingleModMPLSTest.java:41)

GradleSingleModMPProjectTest STANDARD_OUT
    INFO: 2024-11-27T01:52:27.451473: prepareEnv. Entry. ProjectPath: /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/gradle. ProjectName: singleModGradleMP
    INFO: 2024-11-27T01:52:52.559631: UIBotTestUtils.openProjectView Entry
    INFO: 2024-11-27T01:53:03.259262: UIBotTestUtils.openProjectView Exit
    INFO: 2024-11-27T01:53:03.259777: UIBotTestUtils.waitForIndexing Entry
    INFO: 2024-11-27T01:54:03.758775: UIBotTestUtils.waitForIndexing Exit
    INFO: 2024-11-27T01:55:17.396531: prepareEnv. Exit. ProjectName: singleModGradleMP

GradleSingleModMPProjectTest > testCustomStartParametersClearedOnConfigRemoval() STANDARD_OUT
    INFO: 2024-11-27T01:55:17.525613: GradleSingleModMPProjectTest.testCustomStartParametersClearedOnConfigRemoval(). Entry

GradleSingleModMPProjectTest > testCustomStartParametersClearedOnConfigRemoval() FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT16S) for condition function (Menu items containing the Edit Configurations... text were not found) 
        at com.intellij.remoterobot.utils.RepeatUtilsKt$waitFor$2.invoke(RepeatUtils.kt:47)
        at com.intellij.remoterobot.utils.RepeatUtilsKt$waitFor$2.invoke(RepeatUtils.kt:45)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:45)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:33)
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getActionMenuItem(ProjectFrameFixture.java:79)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.deleteLibertyRunConfigurations(UIBotTestUtils.java:2204)
        at io.openliberty.tools.intellij.it.SingleModMPProjectTestCommon.testCustomStartParametersClearedOnConfigRemoval(SingleModMPProjectTestCommon.java:1166)
    
```

File: src/test/resources/ci/scripts/run.sh [hunk 1]
```diff
@@ -190,6 +190,9 @@ main() {
     fi
 
     export JUNIT_OUTPUT_TXT="$currentLoc"/build/junit.out
+    # Run the tests up to 5 times. "SocketTimeoutException" seems to be rare so hopefully 5
+    # repetitions are enough. Also a failure takes about 1 hour and the github time limit is
+    # 6 hours so it is unlikely we could run more than 5 times in one build.
```
Comment (mrglavas) [inline src/test/resources/ci/scripts/run.sh:195]: It's good that we're adding comments, removing unused imports and updating copyrights, but maybe mention in the PR description that that the PR contains some clean-up of previous work in addition to the main work being done here.

**Review by mrglavas — APPROVED** [review]
Looks good. Thanks.

**Review by vaisakhkannan — APPROVED** [review]
Looks good. Thanks @turkeylurkey

File: src/test/resources/ci/scripts/run.sh (hunk 1 above)
Comment (turkeylurkey) [reply src/test/resources/ci/scripts/run.sh:195]: Ok, done!

**Comment by turkeylurkey** [comment]
The Mac failure demonstrated one thing: the first run suffered a SocketTimeoutException but it was aborted by the code in this series of fixes after one hour (not 3hrs for a full run). The failures in the second run look like mouse clicks were not transmitted.

**Comment by turkeylurkey** [comment]
Windows failed trying to debug the server. `148 tests completed, 6 failed, 16 skipped` but just one movie.
