### PR TITLE
Fixes #577 - Quick Fixes which extend Insert annotation missing quick fix .

### LINKED ISSUE #577: Transform the Quick Fixes which extend InsertAnnotationMissingQuickFix to implement the code action participant extension point.
See the initial work completed here: [https://github.com/OpenLiberty/liberty-tools-intellij/issues/304](https://github.com/OpenLiberty/liberty-tools-intellij/issues/304)

In addition to refactoring the code, the code action participants will need to be added to the plugin.xml and the relevant Jakarta EE code action tests should be enabled.

### PR DESCRIPTION
**Pull request by anusreelakshmi934**
Fixes #577

### CODE REVIEW

**Review by dessina-devasia — DISMISSED** [review]

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanConstructorQuickFix.java [hunk 1]
```diff
@@ -17,4 +17,9 @@ public class ManagedBeanConstructorQuickFix extends InsertAnnotationMissingQuick
     public ManagedBeanConstructorQuickFix() {
         super("jakarta.inject.Inject");
     }
+
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanConstructorQuickFix.java:20]: Should update the copyright in this file like all the others.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java [hunk 2]
```diff
@@ -48,29 +55,38 @@ protected void insertAnnotations(Diagnostic diagnostic, JavaCodeActionContext co
...
+    private void insertAndReplaceAnnotation(Diagnostic diagnostic, JavaCodeActionContext context,
+                                            List<CodeAction> codeActions, String annotation) {
         String name = getLabel(annotation);
+        codeActions.add(JDTUtils.createCodeAction(context, diagnostic, name, getParticipantId()));
+    }
+
+    @Override
+    public CodeAction resolveCodeAction(JavaCodeActionResolveContext context) {
+        final CodeAction toResolve = context.getUnresolved();
+        String name = getLabel(ADD_ANNOTATION);
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java:67]: Should retrieve the title from the code action instead of recomputing it here.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java [hunk 3]
```diff
@@ -15,23 +15,30 @@
...
+import java.util.logging.Logger;
 
 import static io.openliberty.tools.intellij.lsp4jakarta.lsp4ij.cdi.ManagedBeanConstants.SCOPE_FQ_NAMES;
 
 public class ManagedBeanQuickFix extends InsertAnnotationMissingQuickFix {
+    private static final Logger LOGGER = Logger.getLogger(ManagedBeanQuickFix.class.getName());
+    private static final String ADD_ANNOTATION = "jakarta.enterprise.context.Dependent";
+
     public ManagedBeanQuickFix() {
         super("jakarta.enterprise.context.Dependent");
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java:43]: Should use the constant you created here to reduce the number of duplicates of this string literal.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationMissingQuickFix.java [hunk 4]
```diff
@@ -73,6 +80,25 @@ public List<? extends CodeAction> getCodeActions(JavaCodeActionContext context,
         return codeActions;
     }
 
+    @Override
+    public CodeAction resolveCodeAction(JavaCodeActionResolveContext context) {
+        final CodeAction toResolve = context.getUnresolved();
+        String name = getLabel(annotations);
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationMissingQuickFix.java:86]: Should retrieve the title from the code action instead of recomputing it here.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java [hunk 5]
```diff
@@ -66,65 +78,83 @@ protected void insertAnnotations(Diagnostic diagnostic, JavaCodeActionContext co
...
+        String annotation = (String) data.getExtendedDataEntry(ANNOTATION_KEY);
+
+        if (diagnosticCode.equals(ServletConstants.DIAGNOSTIC_CODE_FILTER_MISSING_ATTRIBUTE)) {
+            node = context.getCoveringNode();
+            parentType = getBinding(node);
+            annotationNode = getAnnotation(node);
+
+            ArrayList<String> attributesToAdd = new ArrayList<>();
+            attributesToAdd.add(attribute);
+            String name = getLabel(annotation, attribute, "Add");
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java:99]: Should retrieve the title from the code action instead of recomputing it here.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java [hunk 6]
```diff
@@ -66,65 +78,83 @@ protected void insertAnnotations(Diagnostic diagnostic, JavaCodeActionContext co
...
+        }
+
+        if (diagnosticCode.equals(ServletConstants.DIAGNOSTIC_CODE_FILTER_DUPLICATE_ATTRIBUTES)) {
+            node = context.getCoveringNode();
+            parentType = getBinding(node);
+            annotationNode = getAnnotation(node);
+
+            ArrayList<String> attributesToRemove = new ArrayList<>();
+            attributesToRemove.add(attribute);
+            String name = getLabel(annotation, attribute, "Remove");
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java:117]: Should retrieve the title from the code action instead of recomputing it here.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java [hunk 7]
```diff
@@ -66,69 +77,80 @@ protected void insertAnnotations(Diagnostic diagnostic, JavaCodeActionContext co
...
+        String annotation = (String) data.getExtendedDataEntry(ANNOTATION_KEY);
+
+        if (diagnosticCode.equals(ServletConstants.DIAGNOSTIC_CODE_MISSING_ATTRIBUTE)) {
+            node = context.getCoveringNode();
+            parentType = getBinding(node);
+            annotationNode = getAnnotation(node);
+
+            ArrayList<String> attributesToAdd = new ArrayList<>();
+            attributesToAdd.add(attribute);
+            String name = getLabel(annotation, attribute, "Add");
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java:98]: Should retrieve the title from the code action instead of recomputing it here.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java [hunk 8]
```diff
@@ -66,69 +77,80 @@ protected void insertAnnotations(Diagnostic diagnostic, JavaCodeActionContext co
...
+            }
+        }
+        if (diagnosticCode.equals(ServletConstants.DIAGNOSTIC_CODE_DUPLICATE_ATTRIBUTES)) {
+            node = context.getCoveringNode();
+            parentType = getBinding(node);
+            annotationNode = getAnnotation(node);
+
+            ArrayList<String> attributesToRemove = new ArrayList<>();
+            attributesToRemove.add(attribute);
+            String name = getLabel(annotation, attribute, "Remove");
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java:115]: Should retrieve the title from the code action instead of recomputing it here.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java [hunk 9]
```diff
@@ -52,6 +60,10 @@
  *
  */
 public class CompleteFilterAnnotationQuickFix extends InsertAnnotationMissingQuickFix {
+    private static final Logger LOGGER = Logger.getLogger(CompleteServletAnnotationQuickFix.class.getName());
```
Comment (dessina-devasia) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java:63]: Class name different in logger

**Review by dessina-devasia — DISMISSED** [review]
Looks good for me

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanConstructorQuickFix.java (hunk 1 above)
Comment (anusreelakshmi934) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanConstructorQuickFix.java:20]: Updated the Copyrights

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java (hunk 2 above)
Comment (anusreelakshmi934) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java]: Made the necessary changes so that the title is retrieved from `toResolve.getTitle()` .

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java (hunk 3 above)
Comment (anusreelakshmi934) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/cdi/ManagedBeanQuickFix.java]: Made the requested change to use `ADD_ANNOTATION` constant.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationMissingQuickFix.java (hunk 4 above)
Comment (anusreelakshmi934) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/codeAction/proposal/quickfix/InsertAnnotationMissingQuickFix.java]: Made the necessary changes so that the title is retrieved from `toResolve.getTitle()` .

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceAnnotationQuickFix.java [hunk 10]
```diff
@@ -69,15 +70,9 @@ private static void insertAndReplaceAnnotation(Diagnostic diagnostic, JavaCodeAc
...
                     context.getASTRoot(), binding, annotationNode, 0, attributes, annotations);
-
-            // Convert the proposal to LSP4J CodeAction
-            // We need to fix all the annotations so all the changes are combined in this one context.
-            // Therefore, we only need to save the last code action.
-            codeAction = context.convertToCodeAction(proposal, diagnostic);
-        }
-        if (codeAction != null) {
-            codeActions.add(codeAction);
         }
```
[the remark this answers is not in the document]
Comment (anusreelakshmi934) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceAnnotationQuickFix.java]: Modified the PersistenceAnnotationQuickFix class to accomodate the changes.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java (hunk 5 above)
Comment (anusreelakshmi934) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java]: Made the necessary changes so that the title is retrieved from `toResolve.getTitle()`.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java (hunk 6 above)
Comment (anusreelakshmi934) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java]: Made the necessary changes so that the title is retrieved from `toResolve.getTitle()`.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java (hunk 7 above)
Comment (anusreelakshmi934) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java]: Made the necessary changes so that the title is retrieved from `toResolve.getTitle()`.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java (hunk 8 above)
Comment (anusreelakshmi934) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteServletAnnotationQuickFix.java]: Made the necessary changes so that the title is retrieved from `toResolve.getTitle()`.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java (hunk 9 above)
Comment (anusreelakshmi934) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/servlet/CompleteFilterAnnotationQuickFix.java]: Made the change

File: src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java [hunk 11]
```diff
@@ -63,20 +63,22 @@ public void managedBeanAnnotations() throws Exception {
                 DiagnosticSeverity.Error, "jakarta-cdi", "InvalidManagedBeanAnnotation");
 
         assertJavaDiagnostics(diagnosticsParams, utils, d1, d2);
+        String newText1 = "package io.openliberty.sample.jakarta.cdi;\n\nimport jakarta.enterprise.context.*;\nimport jakarta.enterprise.context.Dependent;\n\n" +
```
[the remark this answers is not in the document]
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java]: Formatted

File: src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java [hunk 12]
```diff
@@ -63,20 +63,22 @@ public void managedBeanAnnotations() throws Exception {
...
+                "@RequestScoped\npublic class ManagedBean<T> {\n    @Dependent\n    public int a;\n\n\n    public ManagedBean() {\n        this.a = 10;\n    }\n}\n";
+        String newText = "package io.openliberty.sample.jakarta.cdi;\n\nimport jakarta.enterprise.context.*;\nimport jakarta.enterprise.context.Dependent;\n\n" +
```
[the remark this answers is not in the document]
Comment (anusreelakshmi934) [reply src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/cdi/ManagedBeanTest.java]: Formatted

File: src/test/resources/projects/maven/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/servlet/InvalidWebFilter.java [hunk 13]
```diff
@@ -0,0 +1,11 @@
+package io.openliberty.sample.jakarta.servlet;
+
+import jakarta.servlet.*;
```
[the remark this answers is not in the document]
Comment (anusreelakshmi934) [reply src/test/resources/projects/maven/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/servlet/InvalidWebFilter.java]: Imported jakarta.servlet.Filter

**Review by dessina-devasia — APPROVED** [review]
Looks good for me

**Review by mrglavas — APPROVED** [review]
Looks good now. Thanks.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceAnnotationQuickFix.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (mrglavas) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceAnnotationQuickFix.java]: Can you describe the behavioural changes you made? It would be good for us to document that.

[the remark this answers is not in the document]
Comment (anusreelakshmi934) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/persistence/PersistenceAnnotationQuickFix.java]: Changes made are : 
A new method `resolveCodeAction` is introduced, responsible for resolving code actions by creating a workspace edit based on the proposed changes.
Instead of creating code actions using a custom method `convertToCodeAction` it now utilizes `JDTUtils.createCodeAction`.
The `getParticipantId` method is overridden to return the class name.
