### PR TITLE
Add fix for rechecking the expected hover data

### LINKED ISSUE #1307: Windows automated UI test failure: Mismatch in diagnostic hover data when running the test testJakartaDiagnosticsInJavaPart()
I found the following failure in the Windows automated tests.

```
GradleSingleModJakartaLSTest > testJakartaDiagnosticsInJavaPart() FAILED

    org.opentest4j.AssertionFailedError: Did not find diagnostic help text expected. Looking for Only public methods can be exposed as resource methods
```

https://github.com/user-attachments/assets/5280fee9-1e54-43dc-b151-f1f8538fede8

Build links that contain the above test failure.

https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/13761345004/job/38477962325

https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/13780386943/job/38537458061

https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/13695568849/job/38297126645

This issue might be related to the missing Jakarta quick fix issue: [OpenLiberty/liberty-tools-intellij#748](https://github.com/OpenLiberty/liberty-tools-intellij/issues/748)

### PR DESCRIPTION
**Pull request by vaisakhkannan**
Fixes #1307

Our current test checks for hover data only once and immediately validates the expected data. However, in Windows builds, the initially detected `HoverData` was sometimes incorrect, leading to test failures. This issue might be due to machine slowness, causing a delay in hover data reflection. To address this, the test now checks up to `five` times for the expected data. In some cases, three checks were sufficient, so I set the loop iteration value to five for reliability.

This is how the build logs appear when our expected hover data is not found on the first attempt.

Screenshot 2025-03-13 at 12 04 07 PM

### CODE REVIEW

**Comment by vaisakhkannan** [comment]
Adding a video for reference after applying this PR fix.

Screen Recording 2025-03-13 at 4.07.41 PM.mov

File: src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java [hunk 1]
```diff
@@ -121,10 +121,21 @@ public void testJakartaDiagnosticsInJavaPart() {
             // validate the method signature is no longer set to public
             TestUtils.validateStringNotInFile(pathToSrc.toString(), publicString);
 
-            //there should be a diagnostic for "private" on method signature - move cursor to hover point
+            //there may be a diagnostic for "private" on method signature - move cursor to hover point
```
Comment (turkeylurkey) [inline src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java:124]: Since we are looking for the message for "private" this should still say "should" because that message is what should be there. But you could add a blank after // to match the others in this method.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java [hunk 2]
```diff
@@ -121,10 +121,21 @@ public void testJakartaDiagnosticsInJavaPart() {
...
             UIBotTestUtils.hoverInAppServerCfgFile(remoteRobot, flaggedString, "SystemResource2.java", UIBotTestUtils.PopupType.DIAGNOSTIC);
 
             String foundHoverData = UIBotTestUtils.getHoverStringData(remoteRobot, UIBotTestUtils.PopupType.DIAGNOSTIC);
+
+            // if the LS has not yet poulated the popup data, re-get the popup data
+            for (int i = 0; i<5; i++){
+                if (foundHoverData.contains("method 'getProperties()' is never used")) {
+                    UIBotTestUtils.hoverInAppServerCfgFile(remoteRobot, flaggedString, "SystemResource2.java", UIBotTestUtils.PopupType.DIAGNOSTIC);
+                    foundHoverData = UIBotTestUtils.getHoverStringData(remoteRobot, UIBotTestUtils.PopupType.DIAGNOSTIC);
```
Comment (turkeylurkey) [inline src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java:133]: If we are looping waiting for something to happen a small delay would be appropriate.

Also fix the comment "poulated".

**Review by turkeylurkey — COMMENTED** [review]
.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java (hunk 2 above)
Comment (vaisakhkannan) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java:134]: Thanks @turkeylurkey for the suggestion, I added sleep of 2 seconds and corrected the comment.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java (hunk 1 above)
Comment (vaisakhkannan) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java]: Thanks @turkeylurkey , I added back 'should' and also added a blank.

**Review by dessina-devasia — APPROVED** [review]
Looks Good. Thanks!

File: src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java (hunk 1 above)
Comment (turkeylurkey) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java]: 👍

File: src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java (hunk 2 above)
Comment (turkeylurkey) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModJakartaLSTestCommon.java:134]: 👍

**Review by turkeylurkey — APPROVED** [review]
Good, thank you.
