### PR TITLE
Resolved terminal exception for liberty:start action for lower intellij versions

### LINKED ISSUE #1392: Hit exception while doing Liberty:start action for IntelliJ 2024.3.x and below versions
Hit below exception while doing Liberty:start action for IntelliJ 2024.3.x and below versions
Image
```
java.lang.Throwable: Failed to set TerminalEngine to CLASSIC via reflection: org.jetbrains.plugins.terminal.TerminalEngine PluginClassLoader(plugin=PluginDescriptor(name=Liberty Tools, id=open-liberty.intellij, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2024.3/plugins/liberty-tools-intellij, version=25.0.9-SNAPSHOT, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, moduleName=intellij.terminal.sh, descriptorPath=intellij.terminal.sh.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/terminal, version=243.26574.91, package=org.jetbrains.plugins.terminal.sh, isBundled=true), PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, moduleName=intellij.terminal/cloud, descriptorPath=intellij.terminal.cloud.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/terminal, version=243.26574.91, package=org.jetbrains.plugins.terminal.cloud, isBundled=true), PluginDescriptor(name=Properties, id=com.intellij.properties, moduleName=intellij.properties/copyright, descriptorPath=intellij.properties.copyright.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/properties, version=243.26574.91, package=com.intellij.lang.properties.copyright, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.terminal, descriptorPath=intellij.java.terminal.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/java, version=243.26574.91, package=com.intellij.java.terminal, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.performancePlugin, descriptorPath=intellij.java.performancePlugin.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/java, version=243.26574.91, package=com.intellij.java.performancePlugin, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.compiler.charts, descriptorPath=intellij.java.compiler.charts.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/java, version=243.26574.91, package=com.intellij.java.compiler.charts, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/lib, version=243.26574.91, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/lib, version=243.26574.91, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/lib, version=243.26574.91, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.jvm.analysis.impl, descriptorPath=intellij.jvm.analysis.impl.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/java, version=243.26574.91, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.vcs, descriptorPath=intellij.java.vcs.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/java, version=243.26574.91, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.unscramble, descriptorPath=intellij.java.unscramble.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/java, version=243.26574.91, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.structuralSearch, descriptorPath=intellij.java.structuralSearch.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/java, version=243.26574.91, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/lib, version=243.26574.91, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.featuresTrainer, descriptorPath=intellij.java.featuresTrainer.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/java, version=243.26574.91, package=null, isBundled=true), PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, descriptorPath=plugin.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/terminal, version=243.26574.91, package=org.jetbrains.plugins.terminal, isBundled=true), PluginDescriptor(name=Properties, id=com.intellij.properties, descriptorPath=plugin.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/properties, version=243.26574.91, package=com.intellij.lang.properties, isBundled=true), PluginDescriptor(name=Gradle, id=com.intellij.gradle, descriptorPath=plugin.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/gradle, version=243.26574.91, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, descriptorPath=plugin.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/java, version=243.26574.91, package=null, isBundled=true), PluginDescriptor(name=LSP4IJ, id=com.redhat.devtools.lsp4ij, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2024.3/plugins/lsp4ij, version=0.15.0, package=null, isBundled=false), PluginDescriptor(name=Maven, id=org.jetbrains.idea.maven, descriptorPath=plugin.xml, path=/Applications/IntelliJ IDEA CE 2.app/Contents/plugins/maven, version=243.26574.91, package=null, isBundled=true), )
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at io.openliberty.tools.intellij.util.LibertyProjectUtil.getTerminalWidget(LibertyProjectUtil.java:174)
	at io.openliberty.tools.intellij.actions.LibertyGeneralAction.getTerminalWidgetWithFocus(LibertyGeneralAction.java:175)
	at io.openliberty.tools.intellij.actions.LibertyDevStartAction.runInTerminal(LibertyDevStartAction.java:45)
	at io.openliberty.tools.intellij.actions.LibertyDevStartAction.executeLibertyAction(LibertyDevStartAction.java:38)
	at io.openliberty.tools.intellij.actions.LibertyGeneralAction.actionPerformed(LibertyGeneralAction.java:122)
	at io.openliberty.tools.intellij.LibertyExplorer.executeAction(LibertyExplorer.java:287)
	at io.openliberty.tools.intellij.LibertyExplorer$2.onDoubleClick(LibertyExplorer.java:214)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:16)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:63)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6662)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3394)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:479)
	at java.desktop/java.awt.Component.processEvent(Component.java:6427)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5032)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4577)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:621)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$21(IdeEventQueue.kt:564)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:564)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:917)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:117)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### PR DESCRIPTION
**Pull request by dessina-devasia**
Fixes #1392 

Checked the TerminalEngine enum contains CLASSIC, as it is not available for old intellij versions

### CODE REVIEW

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java [hunk 1]
```diff
@@ -158,20 +158,32 @@ public static ShellTerminalWidget getTerminalWidget(Project project, LibertyModu
...
-                        .invoke(null);
-
                 Class<?> terminalEngineClass = Class.forName("org.jetbrains.plugins.terminal.TerminalEngine");
-                Object classicEngine = Enum.valueOf((Class<Enum>) terminalEngineClass, "CLASSIC");
-                Method setEngineMethod = optionsProviderClass
-                        .getMethod("setTerminalEngine", terminalEngineClass);
-                setEngineMethod.invoke(optionsProviderInstance, classicEngine);
 
-            } catch (ClassNotFoundException | NoSuchMethodException |
-                     IllegalAccessException | InvocationTargetException e) {
```
[the remark this answers is not in the document]
Comment (dessina-devasia) [reply src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:173]: @vaisakhkannan Thank you for raising this. I'll update it.

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java [hunk 2]
```diff
@@ -157,21 +157,21 @@ public static ShellTerminalWidget getTerminalWidget(Project project, LibertyModu
...
-                LOGGER.error("Failed to set TerminalEngine to CLASSIC via reflection: " + e.getMessage());
+                    Class<?> terminalEngineClass = Class.forName("org.jetbrains.plugins.terminal.TerminalEngine");
+                    Object classicEngine = Enum.valueOf((Class<Enum>) terminalEngineClass, "CLASSIC");
+                    Method setEngineMethod = optionsProviderClass
+                            .getMethod("setTerminalEngine", terminalEngineClass);
+                    setEngineMethod.invoke(optionsProviderInstance, classicEngine);
+                } catch (Exception e) {
+                    LOGGER.info("Falling back to default terminal engine.", e);
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:173]: @dessina-devasia I think this should be debug or trace level in the log. I can only imagine this message being useful to debugging control flow through the plugin which is not something a regular user should be concerned about.

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:1]: @dessina-devasia Have you verified that LTI works with the default terminal in IntelliJ 2025.2? I see that the automated builds have been failing and notice several test failures on Windows. Please investigate.

**Review by mrglavas — CHANGES_REQUESTED** [review]
See review comments.

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java [hunk 3]
```diff
@@ -157,21 +157,21 @@ public static ShellTerminalWidget getTerminalWidget(Project project, LibertyModu
...
 
-            } catch (ClassNotFoundException | NoSuchMethodException |
-                     IllegalAccessException | InvocationTargetException e) {
-                LOGGER.error("Failed to set TerminalEngine to CLASSIC via reflection: " + e.getMessage());
+                    Class<?> terminalEngineClass = Class.forName("org.jetbrains.plugins.terminal.TerminalEngine");
+                    Object classicEngine = Enum.valueOf((Class<Enum>) terminalEngineClass, "CLASSIC");
+                    Method setEngineMethod = optionsProviderClass
+                            .getMethod("setTerminalEngine", terminalEngineClass);
+                    setEngineMethod.invoke(optionsProviderInstance, classicEngine);
+                } catch (Exception e) {
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:172]: @dessina-devasia Certain `RuntimeException`s should never be caught and are expected to be thrown up the stack back to the IntelliJ platform to be handled correctly (e.g. a CancellationException). Why was this changed from the more specific list of exceptions?

**Comment by dessina-devasia** [comment]
Please find the below screenshots for different IntelliJ versions

2024.3.6 Terminal (no change)
2024 3 6-terminal-no-change

2025.1.2  Reworked Terminal (by default)
2025 1 2-reworked-default

2025.1.2 Classic (changed by code)
2025 1 2-classic-changed

2025.1.3 Reworked Terminal (by default)
2025 1 3-reworked-default

2025.1.3 Classic (changed by code)
2025 1 3-classic-changed

2025.2 Reworked Terminal (no change)
2025 2-reworked-terminal-no-change

2025.2 Ultimate Reworked Terminal (no change)
2025 2-ultimate-reworked-terminal-no-change

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java
Comment (dessina-devasia) [reply src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:1]: Yes. I've tested with different intellij version. Here is the [detailed comment.](https://github.com/OpenLiberty/liberty-tools-intellij/pull/1393#issuecomment-3302239218). I've checked the b build failures and confirmed nothing related to this PR. I've rerun the build and its success now

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java (hunk 3 above)
Comment (dessina-devasia) [reply src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:172]: @mrglavas I've reverted it back with the specific exception list. Thanks for raising this.

**Review by mrglavas — APPROVED** [review]
Looks good now. Thanks for verifying the test results.

**Review by TrevCraw — APPROVED** [review]
