### PR TITLE
Examine the UI for IntelliJ indexing and wait

### LINKED ISSUE #886: testInsertJakartaCodeSnippetIntoJavaPart()FAILED due to NoSuchElementException
While running UI tests in windows, GradleSingleModJakartaLSTest > `testInsertJakartaCodeSnippetIntoJavaPart`() is getting failed quite a few times due to ` java.util.NoSuchElementException: List is empty.`. If we re ran the tests a couple of times it is getting success.

Attaching failure logs - https://github.com/anusreelakshmi934/liberty-tools-intellij/actions/runs/10064285765/job/27842019395#step:10:836

### PR DESCRIPTION
**Pull request by turkeylurkey**
There is no issue for this fix but it affects several of the issues we have open for automated testing. For instance Anusree was looking at an issue on Windows and she noticed this problem.

Fixes #886

### CODE REVIEW

**Comment by turkeylurkey** [comment]
@mezarin , @ajm01  I added you guys as optional reviewers in case you have valuable guidance. Thank you!

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java [hunk 1]
```diff
@@ -316,7 +316,7 @@ public static void prepareEnv(String projectPath, String projectName) {
 
         // pre-open project tree before attempting to open files needed by testcases
         ProjectFrameFixture projectFrame = remoteRobot.find(ProjectFrameFixture.class, Duration.ofMinutes(2));
-        JTreeFixture projTree = projectFrame.getProjectViewJTree(projectName);
```
Comment (mrglavas) [inline src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java:319]: The comment suggests that this call to `getProjectViewTree()` was intentional and Andy/Ed might have thought it was necessary to have here. Did you mean to remove this? They would more likely have a better understanding of why this was here, assuming they remember.

Comment (turkeylurkey) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java:319]: I only removed it because the result was not used but it might be there for side effects. Unfortunately I wrote this some months ago so I will need to redo the investigation.

Comment (turkeylurkey) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPLSTestCommon.java:319]: My reason was that projTree was not used but now projectFrame is not used. Restoring old code.

File: src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java [hunk 2]
```diff
@@ -1761,6 +1761,22 @@ public static void waitForLTWTextAreaMessage(RemoteRobot remoteRobot, String mes
...
+        String xPath = "//div[@class='InlineProgressPanel']";
+        Locator progressPanelLocator = byXpath(xPath);
+        JLabelFixture progressPanelFixture = projectFrame.find(JLabelFixture.class, progressPanelLocator, Duration.ofSeconds(10));
+
+        RepeatUtilsKt.waitFor(Duration.ofSeconds(waitTime),
+                Duration.ofSeconds(1),
+                "Waiting for indexing message to disappear e.g. Indexing Java 17...",
+                "Indexing did not appear in the Liberty tool window",
+                () -> progressPanelFixture.findAllText().isEmpty());
+    }
```
Comment (TrevCraw) [inline src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java:1779]: Is it possible to hit a scenario where we are checking for indexing before indexing has started? If so, how can we handle that?

Comment (mrglavas) [reply src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java:1779]: I think your question highlights just how tricky it is to make these UI tests reliable. The `RemoteRobot` is provided by JetBrains, right? I wonder if they have a guide or best practices on how to use it so that you get deterministic results when you apply it to the IDE.

Comment (turkeylurkey) [reply src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java:1779]: Ed or Andy faced this issue when detecting the "empty liberty tools window" test. They waited 2s before checking for indexing before checking the window. I'll try to do the same.

Comment (turkeylurkey) [reply src/test/java/io/openliberty/tools/intellij/it/UIBotTestUtils.java:1812]: The test for the empty liberty tools window actually waits for indexing to start and then waits for it to stop. In the current case we could do a similar thing, check the latest code. Let me know if it has become too complex.

**Review by mrglavas — APPROVED** [review]
Reviewed changes with Paul. Looks good. Thanks!

**Comment by turkeylurkey** [comment]
Mac test fails with this error #913 
image

**Review by aparnamichael — APPROVED** [review]
Looks good!!
