### PR TITLE
239 Replace getCanonicalPath with getPath

### LINKED ISSUE #239: error wiyh plugin using latest IntelliJ Ultimate version
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:216)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at io.openliberty.tools.intellij.liberty.lsp.BootstrapPropertiesFileType.isMyFileType(BootstrapPropertiesFileType.java:41)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getByFile(FileTypeManagerImpl.java:783)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:743)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:687)
	at com.intellij.openapi.vfs.VirtualFile.getFileType(VirtualFile.java:356)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getFileType(VirtualFileSystemEntry.java:594)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.createFileViewProvider(FileManagerImpl.java:263)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findViewProvider(FileManagerImpl.java:193)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:362)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:156)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.getFiles(PsiDirectoryImpl.java:150)
	at com.intellij.lang.properties.PropertiesImplUtil.getResourceBundle(PropertiesImplUtil.java:86)
	at com.intellij.lang.properties.PropertiesImplUtil.lambda$getResourceBundleWithCachedFiles$0(PropertiesImplUtil.java:63)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:873)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.lang.properties.PropertiesImplUtil.getResourceBundleWithCachedFiles(PropertiesImplUtil.java:38)
	at com.intellij.lang.properties.PropertiesImplUtil.getResourceBundleFiles(PropertiesImplUtil.java:72)
	at com.intellij.lang.properties.ResourceBundleImpl.getPropertiesFiles(ResourceBundleImpl.java:27)
	at com.intellij.lang.properties.projectView.ResourceBundleNode.getVirtualFile(ResourceBundleNode.java:66)
	at com.intellij.ide.projectView.ProjectViewNode.computeBackgroundColor(ProjectViewNode.java:298)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:77)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:30)
	at com.intellij.ide.scopeView.ScopeViewTreeModel.lambda$getChildren$13(ScopeViewTreeModel.java:386)
	at com.intellij.util.SmartList.forEach(SmartList.java:352)
	at com.intellij.ide.scopeView.ScopeViewTreeModel.getChildren(ScopeViewTreeModel.java:382)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:548)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:443)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:409)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:305)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:109)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:187)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:475)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

### PR DESCRIPTION
**Pull request by TrevCraw**
Fixes #239 

Using IntelliJ's VFS `getCanonicalPath()` method can result in `null` return values and lead to NPE's. The main difference between the VFS `getCanonicalPath()` and `getPath()` is that `getCanonicalPath()` will attempt to resolve any symbolic links present in the path. Testing out various scenarios where `getCanonicalPath()` was previously used, it is not necessary to resolve the symlinks, and therefore no need to call `getCanonicalPath()` over `getPath()`.

The IntelliJ quick doc on `getCanonicalPath()` states:
```
Resolves all symbolic links containing in a path to this file and returns a path to a link target (in platform-independent format).
Note: please use this method judiciously. In most cases VFS clients don't need to resolve links in paths and should work with those provided by a user.
Returns:
getPath() if there are no symbolic links in a file's path; getCanonicalFile().getPath() if the link was successfully resolved; null otherwise
```

### CODE REVIEW

File: src/main/java/io/openliberty/tools/intellij/liberty/lsp/ServerEnvFileType.java [hunk 1]
```diff
@@ -43,7 +43,7 @@ private ServerEnvFileType() {
 
     @Override
     public boolean isMyFileType(@NotNull VirtualFile file) {
-        Path path = Paths.get(file.getCanonicalPath());
+        Path path = Paths.get(file.getPath());
```
Comment (turkeylurkey) [inline src/main/java/io/openliberty/tools/intellij/liberty/lsp/ServerEnvFileType.java:46]: The problem with not using getCanonicalPath() here is that if someone uses a link to make a file appear to be in a directory then it will not pass the matcher in the next line. Can we just use getCanonicalPath() and check for null instead?

**Review by turkeylurkey — CHANGES_REQUESTED** [review]

**Review by evie-lau — APPROVED** [review]

File: src/main/java/io/openliberty/tools/intellij/liberty/lsp/ServerEnvFileType.java (hunk 1 above)
Comment (evie-lau) [reply src/main/java/io/openliberty/tools/intellij/liberty/lsp/ServerEnvFileType.java:46]: Hmm, not sure how common it is for someone to symlink a server.env file, but null checking and using `getPath()` as a backup may be a good idea.

Comment (TrevCraw) [reply src/main/java/io/openliberty/tools/intellij/liberty/lsp/ServerEnvFileType.java:46]: @turkeylurkey I think it depends on which direction the symlink is going. Are you thinking of a scenario where a user opens a symlink outside of the project that is pointing to a server.env inside the project directory?

If the server.env inside the project is a symlink to a file outside the project, we actually do NOT want to resolve the symlink, as that will cause the matcher to fail (I tested this scenario).

Comment (turkeylurkey) [reply src/main/java/io/openliberty/tools/intellij/liberty/lsp/ServerEnvFileType.java:46]: You're right, this is not breaking the way I thought it would.

**Review by turkeylurkey — APPROVED** [review]
