### PR TITLE
Fix  Diagnostic missing for @PositiveOrZero and enabled test

### LINKED ISSUE #781: Diagnostic missing for `@PositiveOrZero`
#### Description: 

When using `@PositiveOrZero` on a `List<String>` I expect a diagnostic message.
image

When you spell it `@PostiveOrZero` it does not compile but the diagnostic and quick fix are generated.
image

#### Specification:

`@PositiveOrZero` annotation can only be used on BigDecimal, BigInteger, byte, short, int, long, float, double (and their respective wrappers) type fields or methods.

 - [x] Must also enable the unit test in BeanValidationTest.java line 157

### PR DESCRIPTION
**Pull request by vaisakhkannan**
Fixes #781
I just enabled the test for diagnostics (d18) and added a test for the corresponding quick fix.

### CODE REVIEW

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationConstants.java [hunk 1]
```diff
@@ -34,7 +34,7 @@ public class BeanValidationConstants {
     public static final String MIN = "jakarta.validation.constraints.Min";
     public static final String MAX = "jakarta.validation.constraints.Max";
     public static final String NEGATIVE_OR_ZERO = "jakarta.validation.constraints.NegativeOrZero";
-    public static final String POSTIVE_OR_ZERO = "jakarta.validation.constraints.PostiveOrZero";
+    public static final String POSTIVE_OR_ZERO = "jakarta.validation.constraints.PositiveOrZero";
```
Comment (turkeylurkey) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationConstants.java:37]: Could you please change the name of the identifier as well? The spelling mistake there may be confusing.

**Review by turkeylurkey — CHANGES_REQUESTED** [review]

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationConstants.java (hunk 1 above)
Comment (vaisakhkannan) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/beanvalidation/BeanValidationConstants.java]: I made the changes @turkeylurkey

**Review by turkeylurkey — APPROVED** [review]

**Review by TrevCraw — APPROVED** [review]
