### PR TITLE
Handle situation when there is no terminal tab to close

### LINKED ISSUE #1238: Exception in automated test when terminal is not open
In one test the terminal was not open.

Image
In this case an automated test tried to close the terminal which was already closed and this exception occurred:
```
com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'ComponentFixture' by '//div[@class='JBTerminalPanel']' in 10s) 
		at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
		at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
		at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
		at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
		at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
		at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
		at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
		at io.openliberty.tools.intellij.it.SingleModMPProjectCfgTestCommon.stopTerminal(SingleModMPProjectCfgTestCommon.java:139)
		at io.openliberty.tools.intellij.it.SingleModMPProjectCfgTestCommon.afterEach(SingleModMPProjectCfgTestCommon.java:124)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:569)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:128)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptAfterEachMethod(TimeoutExtension.java:110)
		at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
		at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
		at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
		at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:520)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeAfterEachMethodAdapter$24(ClassBasedTestDescriptor.java:510)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachMethods$10(TestMethodTestDescriptor.java:243)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:276)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:276)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:275)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachMethods(TestMethodTestDescriptor.java:241)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:142)
		... 63 more
```

### PR DESCRIPTION
**Pull request by turkeylurkey**
Fixes #1238

Add a try/catch block to handle the case where there is no terminal to be found. Just give up and return.

### CODE REVIEW

**Review by mrglavas — APPROVED** [review]
Looks good. Thanks.

**Review by vaisakhkannan — APPROVED** [review]
Looks good. Thanks @turkeylurkey

**Review by dessina-devasia — APPROVED** [review]
Looks good to me

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java [hunk 1]
```diff
@@ -1242,11 +1243,15 @@ public static void deleteDirectoryIfExists(String dirPath) {
...
-        ProjectFrameFixture projectFrame = remoteRobot.find(ProjectFrameFixture.class, Duration.ofSeconds(10));
-        ComponentFixture terminal = remoteRobot.find(ComponentFixture.class, byXpath("//div[@class='JBTerminalPanel']"), Duration.ofSeconds(10));
-
+        ProjectFrameFixture projectFrame;
+        ComponentFixture terminal;
+        try {
+            projectFrame = remoteRobot.find(ProjectFrameFixture.class, Duration.ofSeconds(10));
+            terminal = remoteRobot.find(ComponentFixture.class, byXpath("//div[@class='JBTerminalPanel']"), Duration.ofSeconds(10));
+        } catch (WaitForConditionTimeoutException w) {
+            return; // there is no terminal with a Liberty to stop
```
Comment (vaisakhkannan) [inline src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:1253]: I have a thought, @turkeylurkey . Some tests, like `testStartWithConfigInDebugModeUsingToolbar`, use the debug window. In such cases, if we assume that somehow the debug window is not closed and currently in focus, the terminal tab is not focused, and the Liberty server is also not stopped, adding a return statement in the catch block will cause the method to exit early. Instead of adding a return in the catch block, can we add code to click on the terminal base label in the left toolbar and then proceed with the remaining steps?

Comment (turkeylurkey) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:1253]: In that case I guess we would need to close the debug window before clicking on the terminal base label. Could you open an issue for this and include a screen shot of the type of situation you are imagining?

**Comment by turkeylurkey** [comment]
I reran the failing test runs on the fork and they passed there so I'm going to go ahead and merge. 
Mac failure here:
GradleSingleModMPSIDProjectTest > testStartWithParamsActionUsingSearch() FAILED
    org.opentest4j.AssertionFailedError: testStartWithParamsActionUsingSearch:validateLibertyServerStopped: Exit. Timed out waiting for message CWWKE0036I
Windows failure here:
GradleSingleModMPSIDProjectTest > testRunTestsActionUsingSearch() FAILED
    org.opentest4j.AssertionFailedError: testRunTestsActionUsingSearch:validateProjectStarted: Timed out while waiting for project with resource URI api/resourceand port 9080 to become available.

File: src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java (hunk 1 above)
Comment (vaisakhkannan) [reply src/test/java/io/openliberty/tools/intellij/it/SingleModMPProjectTestCommon.java:1253]: Sure @turkeylurkey
