### PR TITLE
Fixes #198 -- Add code to shift focus correctly for each terminal

### LINKED ISSUE #198: Terminal focus doesn't shift and terminal renaming doesn't work
When we run on a Liberty action on a project, the focus is not automatically pulled to the corresponding terminal window for the project (if it was not already there) even though we set visible and request focus:
https://github.com/OpenLiberty/liberty-tools-intellij/blob/2908d53a16704abbb812a4afb6095e9e3907d58e/src/main/java/io/openliberty/tools/intellij/actions/LibertyGeneralAction.java#L182-L183

Also noting that terminal renaming doesn't work, issue open against JetBrains:  https://youtrack.jetbrains.com/issue/IDEA-297207

See https://github.com/OpenLiberty/liberty-tools-intellij/issues/143#issuecomment-1319348592

Blocked on fixing this until we have the API fixes from Jetbrains

### PR DESCRIPTION
**Pull request by vaisakhkannan**
Fixes #198 -->  Added code to make sure the focus shifts correctly for each terminal when we perform dev-actions, also tested that terminal renaming works properly.

We can close these dependent issues #505, #506, once the PR is merged.

### CODE REVIEW

**Review by dessina-devasia — DISMISSED** [review]
Looks good for me

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java [hunk 1]
```diff
@@ -149,6 +153,27 @@ public static ShellTerminalWidget getTerminalWidget(Project project, LibertyModu
...
+                    break;
+                }
+            }
+            if (contents.length > 0 && index > 0) {
+                Content terminalContent = contents[index];
+                contentManager.setSelectedContent(terminalContent);
+                terminalContent.getComponent().requestFocus();
+            }
+        }
+
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:176]: It would be better to separate the set focus code to its own method in `LibertyProjectUtil.java` which can be called from `getTerminalWidget()` in `LibertyGeneralAction.java`. Can perhaps try using `widget.hasFocus()` to check if the terminal already has focus before calling `setFocus()`.

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java [hunk 2]
```diff
@@ -149,6 +153,27 @@ public static ShellTerminalWidget getTerminalWidget(Project project, LibertyModu
...
+        TerminalToolWindowManager manager = TerminalToolWindowManager.getInstance(project);
+        ToolWindow toolWindow = manager.getToolWindow();
+
+        if (toolWindow != null) {
+            ContentManager contentManager = toolWindow.getContentManager();
+            Content[] contents = contentManager.getContents();
+
+            int index = 0;
+            for (int i = 0; i < contents.length; i++) {
+                if (contents[i].getPreferredFocusableComponent().equals(widget)) {
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:165]: This may no longer apply once the code has been refactored, but consider if `widget == null`. There should be guard for this entire block so that we don't spend time searching for a component that won't be found.

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java (hunk 1 above)
Comment (mrglavas) [reply src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:176]: Should also rename the `getTerminalWidget()` method in `LibertyGeneralAction.java` to reflect the fact that it is setting focus in addition to retrieving the terminal widget.

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java (hunk 2 above)
Comment (vaisakhkannan) [reply src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:177]: @mrglavas , Now Its checking `widget == null` in the if condition

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java (hunk 1 above)
Comment (vaisakhkannan) [reply src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java]: `widget.hasFocus()` always returns false, even though the corresponding terminal widget is `visible` and focused.

Comment (mrglavas) [reply src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java]: I see that you moved the code into `setFocusToWidget()` but its still being called directly by `getTerminalWidget()`. This meant to be moved up to the method you renamed in `LibertyGeneralAction.java`. Did you try this out? Was there an issue with doing this?

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java (hunk 2 above)
Comment (mrglavas) [reply src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:177]: Thanks. I see that.

**Review by mrglavas — CHANGES_REQUESTED** [review]
See recent comments.

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java (hunk 1 above)
Comment (vaisakhkannan) [reply src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java]: I made the changes as per your suggestions

**Review by mrglavas — APPROVED** [review]
Looks good. Thanks for addressing my review comments.

**Review by aparnamichael — APPROVED** [review]
