### PR TITLE
issue 955 - clear run in container module setting on run config deletion

### LINKED ISSUE #955: Deletion of configuration does not remove 'Start in Container' Setting when enabled
Steps to Reproduce 

1. Create a new Liberty run/debug config through the “Run” → “Edit configurations” window in IntelliJ
2. Select the “Run in container” checkbox and add a dev mode parameter (ie. -DhotTests)

Unknown-13

3. Run this configuration
4. Ensure devc starts up and the added parameter is part of the devc command in the terminal
5. Stop the dev mode
6. Click Run > Edit Configurations. In the Run/Debug Configurations window select the run config created and click on ‘-’ to delete it
7. Apply and then click OK ( Run button won't work here)
8.  run the Liberty “Start” action

I can still see the `Start in container` action performing, but the added `Start parameter` has been removed. This issue needs to be fixed. When I checked this feature in the LTI `24.0.6` release, I observed the same behaviour. I believe this could be considered an enhancement/Bug, as deleting a configuration should remove all associated settings that were made in that configuration.

### PR DESCRIPTION
**Pull request by aparnamichael**
Fixes #955 - Deletion of configuration does not remove 'Start in Container' Setting when enabled

### CODE REVIEW

**Comment by turkeylurkey** [comment]
In LibertyModule it says
```
// FIXME not currently being used, need to enable runInContainer checkbox in LibertyRunConfiguration see https://github.com/OpenLiberty/liberty-tools-intellij/issues/160
    private boolean runInContainer;
```
Could you take this comment out since it is no longer applicable?

File: src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java [hunk 1]
```diff
@@ -40,8 +41,11 @@ public void runConfigurationRemoved(@NotNull RunnerAndConfigurationSettings sett
             try {
                 VirtualFile vBuildFile = VfsUtil.findFile(Paths.get(runConfig.getBuildFile()), true);
                 LibertyModule libertyModule = libertyModules.getLibertyModule(vBuildFile);
-                if (libertyModule != null && libertyModule.getCustomStartParams().equals(runConfig.getParams())) {
-                    libertyModule.setCustomStartParams(""); // clear the custom params
+                if (libertyModule != null) {
+                    libertyModule.setRunInContainer(false); // clear the run in container checkbox
```
Comment (turkeylurkey) [inline src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java:45]: Here we can see that every time `setCustomStartParams()` is called we also need to call `setRunInContainer()`. This is done in `LibertyRunConfiguration`. Could you open an issue to redesign this interface so that the params and the boolean must be set in one call? Now may not be a good time to redesign this interface.

**Review by turkeylurkey — CHANGES_REQUESTED** [review]

File: src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java [hunk 2]
```diff
@@ -40,8 +41,11 @@ public void runConfigurationRemoved(@NotNull RunnerAndConfigurationSettings sett
...
+                    if (libertyModule.getCustomStartParams().equals(runConfig.getParams())) {
```
Comment (TrevCraw) [inline src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java:46]: @aparnamichael do you know the reasoning behind this check? What is the reason we don't just go ahead and clear the custom params every time a run configuration is removed?

File: src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java (hunk 1 above)
Comment (TrevCraw) [inline src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java:45]: I think the comment "clear the run in container checkbox" could be confusing, since it is not actually doing anything to the run in container checkbox directly. This is setting the libertyModule to use a regular start instead of a container start.

File: src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java (hunk 2 above)
Comment (mrglavas) [reply src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java:46]: @aparnamichael I was just reviewing with @TrevCraw and have similar questions.

Comment (aparnamichael) [reply src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java:46]: @mrglavas @TrevCraw These condition is there in the initial file commit. I also think that condition is not needed. But not sure whether that will introduce any new bugs.

File: src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java (hunk 1 above)
Comment (aparnamichael) [reply src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java]: @turkeylurkey This means we should have a single method for eg: setParamsAndRunInContainer(String params, Boolean runInContainer)  in LibertyRunConfiguration ?
If we implement a single method like this, when a user checks the 'Run In Container' option, we also need to pass parameters along with the action of enabling or disabling the checkbox, correct?

File: src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java (hunk 2 above)
Comment (TrevCraw) [reply src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java:46]: Looking into this further, it looks like the condition is to ensure that the run config being deleted is the one that was last run for this particular Liberty module. One Liberty module can have many run configs associated with it. If a user deletes a run config that was not the last one run, then we should not be resetting the Liberty module params to the default values. The same logic should apply for the "run in container" setting.

Comment (TrevCraw) [reply src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java:46]: As a side note, the current "check" to see if a config is last one run is not foolproof. It is possible configs could be identical. Configs could also have all the same custom dev mode params and have other differences (like the "run in container" setting). 

@mrglavas I think this just further shows a larger re-design is required, as you recommended in our discussion. 

@aparnamichael, as @turkeylurkey suggested in another comment, please open an issue for redesign. I would suggest a generic issue like "Redesign the relationship between Liberty module and run configurations". We can put the specific suggestion from @turkeylurkey in there, but @mrglavas recommended an even bigger overhaul of the design.

Comment (aparnamichael) [reply src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java:46]: @turkeylurkey and @TrevCraw created a new issue for re-design. https://github.com/OpenLiberty/liberty-tools-intellij/issues/977

Comment (turkeylurkey) [reply src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java:46]: Added more detail to that issue.

File: src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java (hunk 1 above)
Comment (turkeylurkey) [reply src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java]: Yes, but we will have the Run configuration open in the UI when the checkbox is used. This is part of #977.

File: src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java [hunk 3]
```diff
@@ -40,8 +41,11 @@ public void runConfigurationRemoved(@NotNull RunnerAndConfigurationSettings sett
             try {
                 VirtualFile vBuildFile = VfsUtil.findFile(Paths.get(runConfig.getBuildFile()), true);
                 LibertyModule libertyModule = libertyModules.getLibertyModule(vBuildFile);
-                if (libertyModule != null && libertyModule.getCustomStartParams().equals(runConfig.getParams())) {
-                    libertyModule.setCustomStartParams(""); // clear the custom params
+                if (libertyModule != null) {
+                    libertyModule.setRunInContainer(false); // clear the run in container setting for the Liberty module.
```
Comment (turkeylurkey) [inline src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java:45]: The change to `run in container` should only happen if the parameters are equal. Move this line after the `setCustomStartParams("")` line, inside the `if`.

**Review by turkeylurkey — CHANGES_REQUESTED** [review]

**Review by TrevCraw — APPROVED** [review]

**Review by turkeylurkey — APPROVED** [review]
Thank you.

File: src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java (hunk 3 above)
Comment (turkeylurkey) [reply src/main/java/io/openliberty/tools/intellij/runConfiguration/LibertyRunManagerListener.java]: Looks good.
