### PR TITLE
Fixes issue 846 - usage of APIs scheduled for removal #855

### LINKED ISSUE #846: usage of APIs scheduled for removal
IDE version - 2024.1.4

There are 20 usages of scheduled for removal API.

Scheduled for removal fields usages (11)
- [x] PsiType.VOID (4) (scheduled for removal in a future release)
- [x] PsiType.BOOLEAN (1) (scheduled for removal in a future release)
- [x] PsiType.BYTE (1) (scheduled for removal in a future release)
- [x] PsiType.DOUBLE (1) (scheduled for removal in a future release)
- [x] PsiType.FLOAT (1) (scheduled for removal in a future release)
- [x] PsiType.INT (1) (scheduled for removal in a future release)
- [x] PsiType.LONG (1) (scheduled for removal in a future release)
- [x] PsiType.SHORT (1) (scheduled for removal in a future release)

Scheduled for removal classes usages (4)
- [x] TerminalView (3) (scheduled for removal in a future release)
- [x] LayoutBuilder (1) (scheduled for removal in a future release) - **_The fix needs to be implemented in the lsp4ij plugin._**

Scheduled for removal methods usages (4)
- [x] ProjectManagerListener.projectOpened(Project) (1) (scheduled for removal in a future release) **_The fix needs to be implemented in the lsp4ij plugin._**
- [x] LayoutKt.panel(LCFlags[], String, Function1) (1) (scheduled for removal in a future release)  **_The fix needs to be implemented in the lsp4ij plugin._**
- [x] MavenGeneralSettings.getMavenHome() (1) (scheduled for removal in a future release) - **_The changes are available in main branch_**
- [x] MavenUtil.resolveMavenHomeDirectory(String) (1) (scheduled for removal in a future release) **_The changes are available in main branch_**

Scheduled for removal enum usage (1)

- [x] LCFlags (1) (scheduled for removal in a future release)  **_The fix needs to be implemented in the lsp4ij plugin._**
Deprecated enum LCFlags is referenced in AbstractLSPInlayHintsProvider$2.createComponent(...). This enum will be removed in a future release

### PR DESCRIPTION
**Pull request by aparnamichael**
Fixes #846 
There are 20 usages of scheduled for removal API.

- Scheduled for removal fields usages (11)
- Scheduled for removal classes usages (4)
- Scheduled for removal methods usages (4)
- Scheduled for removal enum usage (1)

### CODE REVIEW

**Comment by aparnamichael** [comment]
Addressed Vaisakh's review comments.
1. Can you explain the usage of method toShellJediTermWidgetOrThrow()?

Answer: 
This is the definition of toShellJediTermWidgetOrThrow.

public static @NotNull ShellTerminalWidget toShellJediTermWidgetOrThrow(@NotNull TerminalWidget widget) {
    return (ShellTerminalWidget)Objects.requireNonNull(JBTerminalWidget.asJediTermWidget(widget));
  }
This method is basically used to typecast the widget to ShellTerminalWidget object. JBTerminalWidget.asJediTermWidge - This method checks whether widget is an instanceof TerminalWidgetBridge. If yes, it will return bridge.widget() or else returns null. Then the 'requireNonNull' method will check whether 'JBTerminalWidget.asJediTermWidget(widget)' returns null or not. If it is null it will throw an exception or else it will type cast the object to ShellTerminalWidget.

When we were using 'createLocalShellWidget' method of TerminalView class. It was doing the same.

```
  fun createLocalShellWidget(workingDirectory: String?,
                             tabName: @Nls String?,
                             requestFocus: Boolean): ShellTerminalWidget {
    return ShellTerminalWidget.toShellJediTermWidgetOrThrow(
      toolWindowManager.createShellWidget(workingDirectory, tabName, requestFocus, true))
  }
  
```
  
  2. What is the difference between the old, deprecated methods PsiPrimitiveType and PsiType? I see that you changed the code to replace both deprecated methods with the PsiTypes method."

Answer: 
Both are Jetbrain's classes.
PsiPrimitiveType class - Representation of Java type (primitive type, array or class type).

```
**Deprecated constants**
All static fields in PsiPrimitiveType class representing instances of PsiPrimitiveType are deprecated. It was done to avoid deadlocks during initialization of the class. According to section 5.5  of JVM specification, when a class is initialized, JVM firsly synchronizes on an initialization lock specific for that class, then initializes its super class and then computes initializers for its static fields. So because of these fields initialization of PsiType performs initialization of PsiPrimitiveType, and initialization of PsiPrimitiveType performs initialization of PsiType because its the super class of its super class. Therefore, if one thread starts initialization of PsiType, and another thread starts initialization of PsiPrimitiveType at the same time, it'll result in a deadlock. In order to avoid this, methods from PsiTypes must be used to get instances of the primitive types.
```
As suggested by Jetbrains we are using PsiTypes methods to get the PsiPrimititveType constants, instead of accessing them directly.

This how PsiTypes method works.

```
public static @NotNull PsiPrimitiveType voidType() { 
    return VOID; 
  }
```

3. Removed all the unused imports.

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java [hunk 1]
```diff
@@ -18,6 +18,7 @@
 import com.intellij.psi.search.FilenameIndex;
 import com.intellij.psi.search.GlobalSearchScope;
 import com.intellij.terminal.JBTerminalWidget;
+import com.intellij.terminal.ui.TerminalWidget;
```
Comment (aparnamichael) [inline src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:21]: @vaisakhkannan We need this import, we are using this class in Line no.240

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java [hunk 2]
```diff
@@ -149,10 +149,13 @@ public static ArrayList<BuildFile> getRemovableMavenBuildFiles(Project project)
      * @param createWidget  true if a new widget should be created
      * @return ShellTerminalWidget or null if it does not exist
      */
-    public static ShellTerminalWidget getTerminalWidget(Project project, LibertyModule libertyModule, boolean createWidget, TerminalView terminalView, ShellTerminalWidget widget) {
+    public static ShellTerminalWidget getTerminalWidget(Project project, LibertyModule libertyModule, boolean createWidget,
+                                                        TerminalToolWindowManager terminalToolWindowManager, ShellTerminalWidget widget) {
         if (widget == null && createWidget) {
             // create a new terminal tab
-            ShellTerminalWidget newTerminal = terminalView.createLocalShellWidget(project.getBasePath(), libertyModule.getName(), true);
+            ShellTerminalWidget newTerminal = ShellTerminalWidget.toShellJediTermWidgetOrThrow(
```
Comment (aparnamichael) [inline src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:156]: Can you explain the usage of method toShellJediTermWidgetOrThrow()?

Answer: @vaisakhkannan 
This is the definition of toShellJediTermWidgetOrThrow.

```
public static @NotNull ShellTerminalWidget toShellJediTermWidgetOrThrow(@NotNull TerminalWidget widget) {
    return (ShellTerminalWidget)Objects.requireNonNull(JBTerminalWidget.asJediTermWidget(widget));
  }
```
This method is basically used to typecast the widget to ShellTerminalWidget object.
JBTerminalWidget.asJediTermWidge - This method checks whether widget is an instanceof TerminalWidgetBridge. If yes, it will return bridge.widget() or else returns null. Then the 'requireNonNull' method will check whether 'JBTerminalWidget.asJediTermWidget(widget)' returns null or not. If it is null it will throw an exception or else it will type cast the object to ShellTerminalWidget.

When we were using 'createLocalShellWidget' method of TerminalView class. It was doing the same.

```
  fun createLocalShellWidget(workingDirectory: String?,
                             tabName: @Nls String?,
                             requestFocus: Boolean): ShellTerminalWidget {
    return ShellTerminalWidget.toShellJediTermWidgetOrThrow(
      toolWindowManager.createShellWidget(workingDirectory, tabName, requestFocus, true))
  }
  
```

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/PostConstructReturnTypeQuickFix.java [hunk 3]
```diff
@@ -72,7 +73,7 @@ public CodeAction resolveCodeAction(JavaCodeActionResolveContext context) {
 
         assert parentType != null;
         ChangeCorrectionProposal proposal = new ModifyReturnTypeProposal(TITLE_MESSAGE, context.getSource().getCompilationUnit(),
-                context.getASTRoot(), parentType, 0, PsiPrimitiveType.VOID);
+                context.getASTRoot(), parentType, 0, PsiTypes.voidType());
```
Comment (aparnamichael) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/PostConstructReturnTypeQuickFix.java:76]: What is the difference between the old, deprecated methods PsiPrimitiveType and PsiType? I see that you changed the code to replace both deprecated methods with the PsiTypes method.

Answer: @vaisakhkannan 
Both are Jetbrain's classes.
PsiPrimitiveType class - Representation of Java type (primitive type, array or class type).

**Deprecated constants**
All static fields in PsiPrimitiveType class representing instances of PsiPrimitiveType are deprecated. It was done to avoid deadlocks during initialization of the class. According to section 5.5  of JVM specification, when a class is initialized, JVM firsly synchronizes on an initialization lock specific for that class, then initializes its super class and then computes initializers for its static fields. So because of these fields initialization of PsiType performs initialization of PsiPrimitiveType, and initialization of PsiPrimitiveType performs initialization of PsiType because its the super class of its super class. Therefore, if one thread starts initialization of PsiType, and another thread starts initialization of PsiPrimitiveType at the same time, it'll result in a deadlock. In order to avoid this, methods from PsiTypes must be used to get instances of the primitive types.
As suggested by Jetbrains we are using PsiTypes methods to get the PsiPrimititveType constants, instead of accessing them directly.

This how PsiTypes method works.

public static @NotNull PsiPrimitiveType voidType() { 
    return VOID; 
  }

**Comment by aparnamichael** [comment]
@vaisakhkannan Remove all the unused imports

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/PostConstructReturnTypeQuickFix.java (hunk 3 above)
Comment (vaisakhkannan) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/annotations/PostConstructReturnTypeQuickFix.java:76]: Thanks @aparnamichael for the explanation.

File: src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java (hunk 2 above)
Comment (vaisakhkannan) [reply src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java:156]: Thanks @aparnamichael for the explanation.

**Review by vaisakhkannan — DISMISSED** [review]
Looks good to me .Thanks!

File: src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java [hunk 4]
```diff
@@ -1,5 +1,5 @@
 /*******************************************************************************
- * Copyright (c) 2019-2020 Red Hat, Inc.
+ * Copyright (c) 2019-2020, 2024 Red Hat, Inc.
```
Comment (mrglavas) [inline src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java:2]: The copyright format for the source files is YEAR1, YEAR2 where YEAR1 is the first year of copyright and YEAR2 is the most recent update. Please fix.

Comment (aparnamichael) [reply src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java]: @mrglavas updated the header.

**Review by vaisakhkannan — APPROVED** [review]

**Review by mrglavas — APPROVED** [review]
Looks good. Thanks.

**Review by TrevCraw — APPROVED** [review]
