### PR TITLE
Fixes issue #1513: Sync up changes for Invalid Inject Qualifier Diagnostics from lsp4jakarta to intelliJ

### LINKED ISSUE #1513: Sync Invalid qualifier in injector-independent classes diagnostics from lsp4jakarta to IntelliJ
- [ ] lsp4jakarta issue: https://github.com/eclipse-lsp4jakarta/lsp4jakarta/issues/758

lsp4jakarta PR: https://github.com/eclipse-lsp4jakarta/lsp4jakarta/pull/796

### PR DESCRIPTION
**Pull request by archana-1924**
Fixes #1513

### CODE REVIEW

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DIUtils.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
+package io.openliberty.tools.intellij.lsp4jakarta.lsp4ij.di;
```
Comment (venmanyarun) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DIUtils.java:13]: add copyright to the new file

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DIUtils.java [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+    public static boolean isQualifier(PsiAnnotation annotation, PsiJavaFile unit, PsiClass type) {
+        boolean hasBuiltInQualifier = BUILT_IN_QUALIFIERS.stream().anyMatch(qualifier -> {
+            return isMatchedJavaElement(type, annotation.getQualifiedName(), qualifier);
+        });
+        if (!hasBuiltInQualifier) {
+            PsiJavaCodeReferenceElement ref = annotation.getNameReferenceElement();
+            PsiElement resolved = ref != null ? ref.resolve() : null;
+            if (resolved instanceof PsiClass metaAnnotationClass) {
+                for (PsiAnnotation metaAnnotation : metaAnnotationClass.getAnnotations()) {
+                    return isMatchedJavaElement(type, metaAnnotation.getQualifiedName(), QUALIFIER_META);
```
Comment (venmanyarun) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DIUtils.java]: is this logic correct?

The loop returns inside the first iteration, making it only check the first meta-annotation:

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionConstants.java [hunk 3]
```diff
@@ -27,4 +30,20 @@ public class DependencyInjectionConstants {
...
     public static final String DIAGNOSTIC_CODE_INJECT_INNER_CLASS= "RemoveInjectForInnerClass";
+    public static final String DIAGNOSTIC_CODE_INJECT_INVALID_QUALIFIER= "RemoveInvalidQualifier";
+
+    public static final Set<String> CDI_ANNOTATIONS_FQ = Set.of("jakarta.enterprise.context.ApplicationScoped",
+            "jakarta.enterprise.context.ConversationScoped", "jakarta.enterprise.context.RequestScoped",
+            "jakarta.enterprise.context.SessionScoped", "jakarta.enterprise.context.NormalScope",
+            "jakarta.Interceptor", "jakarta.Decorator", "jakarta.enterprise.inject.Stereotype",
+            "jakarta.enterprise.context.Dependent");
+
+    public static final List<String> BUILT_IN_QUALIFIERS = List.of(
```
Comment (venmanyarun) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionConstants.java]: why some of these are Set and others are List?

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 4]
```diff
@@ -75,6 +77,25 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
...
+                    if(isMatchedJavaElement(type, annotation.getQualifiedName(), INJECT_FQ_NAME)){
+                        isInject = true;
+                    }else{
+                        String matchedAnnotation = getMatchedJavaElementName(type, annotation.getQualifiedName(), IMPLICIT_QUALIFIERS.toArray(String[]::new));
+                        if(matchedAnnotation!=null){
+                            fqNames.add(matchedAnnotation);
+                        }
+                    }
+                }
+                if (fqNames.equals(IMPLICIT_QUALIFIERS)) {
```
Comment (venmanyarun) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: This only continues if BOTH implicit qualifiers are present. What if only one is present?

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 5]
```diff
@@ -75,6 +77,25 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
...
+                    continue;
+                }else {
+                    //Finding and generating invalid inject qualifier diagnostics for fields in parent class
+                    List<PsiAnnotation> qualifiers = getQualifiers(field.getAnnotations(), unit, type);
+                    if (isInject && qualifiers.size() > 1 && !isCdiScoped) {
```
Comment (venmanyarun) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: so once inject is true, it would generate diagnostics for all annotations ?

File: src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/di/DependencyInjectionTest.java [hunk 6]
```diff
@@ -318,4 +318,44 @@ public void DependencyInjectionDiagnostics() throws Exception {
         JakartaForJavaAssert.assertJavaCodeAction(codeActionParams, utils, ca, ca1);
 
     }
+
+    @Test
+    public void InvalidInjectQualifiersDI() throws Exception {
```
Comment (venmanyarun) [inline src/test/java/io/openliberty/tools/intellij/lsp4jakarta/it/di/DependencyInjectionTest.java:323]: Shouldnt we have some test for CDI-scoped classes (which should be allowed to have multiple qualifiers) ?

**Review by venmanyarun — CHANGES_REQUESTED** [review]

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java (hunk 4 above)
Comment (archana-1924) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: This logic was implemented for the use case where @Inject, @Default and @Any specifically comes together. It shouldn't throw diagnostics in such cases. Rest of the logic where one of them is used with any other custom qualifier is handled below.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java (hunk 5 above)
Comment (archana-1924) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: If field/method is Inject type and used along with more than 1 un-allowed qualifier and class is not CDI scoped, then yes, it would generate.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DIUtils.java (hunk 2 above)
Comment (archana-1924) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DIUtils.java]: Updated logic to streams to avoid order confusion.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionConstants.java (hunk 3 above)
Comment (archana-1924) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionConstants.java]: Either of them could be used, to maintain uniformity, changed to Set.

**Review by venmanyarun — DISMISSED** [review]

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 7]
```diff
@@ -19,11 +19,10 @@
 import io.openliberty.tools.intellij.lsp4jakarta.lsp4ij.Messages;
 import org.eclipse.lsp4j.Diagnostic;
 import org.eclipse.lsp4j.DiagnosticSeverity;
-
 import static io.openliberty.tools.intellij.lsp4jakarta.lsp4ij.di.DependencyInjectionConstants.*;
 
-import java.util.ArrayList;
-import java.util.List;
+import java.util.*;
```
Comment (Joseph-Bineesh) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: Any reason to import all utilities classes?

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 8]
```diff
@@ -113,14 +134,25 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
...
                     }
-
                     for (PsiParameter param : method.getParameterList().getParameters()) {
                         if (isNonStaticInnerClass(type, param.getType())) {
                             String msg = Messages.getMessage("InjectNonStaticInnerClass");
                             diagnostics.add(createDiagnostic(method, unit, msg,
                                     DIAGNOSTIC_CODE_INJECT_INNER_CLASS, method.getReturnType().getInternalCanonicalText(),
                                     DiagnosticSeverity.Error));
                         }
+                        if(new HashSet<>(getMatchedJavaElementNames(type, Arrays.stream(param.getAnnotations())
```
Comment (Joseph-Bineesh) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: Is it better to refactor to a hashes assignment to a variable and after check if condition for readability.?

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 9]
```diff
@@ -133,9 +165,119 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
...
+                            List<PsiAnnotation> qualifiers = getQualifiers(innerField.getAnnotations(), unit, type);
+                            if (isInjectInner && qualifiers.size() > 1 && !isCdiScoped) {
+                                createInvalidInjectQualifierFieldDiagnostics(unit, diagnostics, innerField);
+                            }
+                        }
+                    }
+                for(PsiMethod innerMethod: innerClass.getMethods()){
+                    if (containsAnnotation(type, innerMethod.getAnnotations(), INJECT_FQ_NAME)) {
+                        for (PsiParameter param : innerMethod.getParameterList().getParameters()) {
+                            if(new HashSet<>(getMatchedJavaElementNames(type, Arrays.stream(param.getAnnotations())
```
Comment (Joseph-Bineesh) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: Seems the same code block in two places. Can you make it as a private method and use it

**Review by Joseph-Bineesh — CHANGES_REQUESTED** [review]

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java (hunk 7 above)
Comment (archana-1924) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: It came in when we auto-import suggestions. Can replace it with separate 6 imports.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 10]
```diff
@@ -174,43 +158,95 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
...
+                .map(PsiAnnotation::getQualifiedName)
+                .filter(Objects::nonNull)
+                .collect(Collectors.toSet()).toArray(String[]::new);
+        Set paramAnnotationsFQ = new HashSet<>(getMatchedJavaElementNames(type, paramAnnotations, implicitQualifiers));
+        if(paramAnnotationsFQ.equals(IMPLICIT_QUALIFIERS)){
+            return;
+        }else {
+            //Finding and generating invalid inject qualifier diagnostics for method parameters
+            List<PsiAnnotation> qualifiers = new ArrayList<>();
+            if(isParent)
```
Comment (Joseph-Bineesh) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: Use { } for better readability. I can see if, else, if  and the last if is not part of first two.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 11]
```diff
@@ -133,9 +149,171 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
...
+     * @param isInject
+     * @param isCdiScoped
+     */
+    private void checkInvalidQualifiersForField(PsiJavaFile unit, List<Diagnostic> diagnostics, PsiClass type, PsiField field, Set<String> fqNames, boolean isInject, boolean isCdiScoped) {
+        if (fqNames.equals(IMPLICIT_QUALIFIERS)) {
+            return;
+        }else {
+            //Finding and generating invalid inject qualifier diagnostics for fields in parent class
+            List<PsiAnnotation> qualifiers = getQualifiers(field.getAnnotations(), unit, type);
+            if (isInject && qualifiers.size() > 1 && !isCdiScoped) {
```
Comment (Joseph-Bineesh) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: Can we check isInject  && !isCdiScoped  before call to getQualifiers? we can avoid this call if condition fails.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 12]
```diff
@@ -133,9 +149,171 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
...
+        if(paramAnnotationsFQ.equals(IMPLICIT_QUALIFIERS)){
+            return;
+        }else {
+            //Finding and generating invalid inject qualifier diagnostics for method parameters
+            List<PsiAnnotation> qualifiers = new ArrayList<>();
+            if(isParent)
+                qualifiers = getQualifiers(param.getAnnotations(), unit, type);
+            else
+                qualifiers = getQualifiers(method.getAnnotations(), unit, type);
+            if (qualifiers.size() > 1 && !isCdiScoped) {
```
Comment (Joseph-Bineesh) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: Check isCdiScoped before getting Qualifier's. We can avoid calls if condition fails.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 13]
```diff
@@ -133,9 +149,171 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
...
+
+    /**
+     * createInvalidInjectQualifierMethodDiagnostics
+     * @description Method to create diagnostics invalid inject qualifiers for methods.
+     * @param unit
+     * @param diagnostics
+     * @param method
+     */
+    private void createInvalidInjectQualifierMethodDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics, PsiMethod method) {
+        if (isConstructorMethod(method))
```
Comment (Joseph-Bineesh) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: Use {} if more than one line after formatting the code for better readability

**Review by Joseph-Bineesh — CHANGES_REQUESTED** [review]

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 14]
```diff
@@ -75,6 +82,17 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
                                 DiagnosticSeverity.Error));
                     }
                 }
+                boolean isInject = false;
+                Set<String> fqNames = new HashSet<>();
+                for(PsiAnnotation annotation: field.getAnnotations()){
+                    if(isMatchedJavaElement(type, annotation.getQualifiedName(), INJECT_FQ_NAME)) {
+                        isInject = true;
+                    }
```
Comment (Joseph-Bineesh) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: Do a source format. I expect else and closing brace of if in the same line.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 15]
```diff
@@ -133,9 +151,184 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
...
             }
+            //Checking if inner classes have more than one qualifier in fields or method params
+            for(PsiClass innerClass: type.getInnerClasses()) {
+                for(PsiField innerField: innerClass.getFields()) {
+                    boolean isInjectInner = false;
+                    Set<String> fqNamesInner = new HashSet<>();
+                    for(PsiAnnotation annotation: innerField.getAnnotations()) {
+                        if(isMatchedJavaElement(type, annotation.getQualifiedName(), INJECT_FQ_NAME)) {
+                            isInjectInner = true;
+                            }
```
Comment (Joseph-Bineesh) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: Do a source format. I expect else and closing brace of if in the same line.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 16]
```diff
@@ -133,9 +151,184 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
...
+     * @param field
+     * @param fqNames
+     * @param isInject
+     * @param isCdiScoped
+     */
+    private void checkInvalidQualifiersForField(PsiJavaFile unit, List<Diagnostic> diagnostics, PsiClass type, PsiField field, Set<String> fqNames, boolean isInject, boolean isCdiScoped) {
+        if (isInject && !isCdiScoped) {
+            if (fqNames.equals(IMPLICIT_QUALIFIERS)) {
+                return;
+            }
```
Comment (Joseph-Bineesh) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: Do a source format. I expect else and closing brace of if in the same line.

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 17]
```diff
@@ -133,9 +151,184 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
...
+     * @param unit
+     * @param diagnostics
+     * @param type
+     * @param field
+     * @param fqNames
+     * @param isInject
+     * @param isCdiScoped
+     */
+    private void checkInvalidQualifiersForField(PsiJavaFile unit, List<Diagnostic> diagnostics, PsiClass type, PsiField field, Set<String> fqNames, boolean isInject, boolean isCdiScoped) {
+        if (isInject && !isCdiScoped) {
```
Comment (Joseph-Bineesh) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: Can we check this condition before calling checkInvalidQualifiersForField? Any reason it pass it as param and just check inside method?

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java [hunk 18]
```diff
@@ -133,9 +151,184 @@ public void collectDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics) {
...
+     * @param unit
+     * @param diagnostics
+     * @param type
+     * @param method
+     * @param param
+     * @param implicitQualifiers
+     * @param isCdiScoped
+     */
+    private void checkInvalidQualifierMethodDiagnostics(PsiJavaFile unit, List<Diagnostic> diagnostics, PsiClass type, PsiMethod method, PsiParameter param, String[] implicitQualifiers, boolean isCdiScoped, boolean isParent) {
+        if(!isCdiScoped) {
```
Comment (Joseph-Bineesh) [inline src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: Can we avoid call to this method if !isCdiScoped? Should we pass it as param and check inside method?

**Review by Joseph-Bineesh — CHANGES_REQUESTED** [review]

File: src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java (hunk 14 above)
Comment (archana-1924) [reply src/main/java/io/openliberty/tools/intellij/lsp4jakarta/lsp4ij/di/DependencyInjectionDiagnosticsCollector.java]: It was on the same line initially, I changed it for indentation. Changed it back to original.

**Review by Joseph-Bineesh — APPROVED** [review]
LGTM

**Review by venmanyarun — DISMISSED** [review]

**Review by turkeylurkey — APPROVED** [review]
Looks good.

**Review by venmanyarun — APPROVED** [review]
